import {
  LuHouse,
  LuChartColumn,
  LuBuilding2,
  LuLayoutGrid,
  LuTag,
  LuArrowLeftRight,
  LuUserRound,
  LuLogOut,
  LuBadgeDollarSign,
  LuBanknote,
  LuHash,
  LuBarcode,
  LuTriangleAlert,
  LuPackage,
  LuTextCursorInput,
  LuMail,
  LuLock,
  LuCalculator,
  LuInbox,
  LuPlus,
  LuSave,
  LuX,
  LuPencil,
  LuTrash2,
  LuCircleCheck,
  LuChevronDown,
  LuChevronRight,
  LuArrowDown,
  LuArrowUp,
  LuWarehouse,
  LuShoppingCart,
  LuReceiptText,
  LuTruck,
  LuUsers,
  LuContact,
  LuSettings,
  LuBell,
  LuSparkles,
  LuStore,
  LuGlobe,
  LuBox,
  LuCrown,
  LuFileText,
  LuSend,
  LuTrendingUp,
  LuTrendingDown,
  LuDownload,
  LuSearch,
  LuPrinter,
  LuBan,
  LuCheck,
  LuPhone,
  LuMapPin,
  LuIdCard,
  LuPercent,
  LuCreditCard,
  LuSmartphone,
  LuWallet,
  LuLandmark,
  LuPackageCheck,
  LuClipboardList,
  LuCalendarClock,
  LuArrowUpRight,
  LuMinus,
  LuInfinity,
  LuZap,
  LuBrain,
  LuScanEye,
  LuMapPinned,
} from "react-icons/lu";
import logo from "../assets/logo.png";

// Íconos y recursos compartidos de la interfaz (set Lucide, trazo uniforme).
export const v = {
  logo,
  // navegación y módulos
  iconoinicio: LuHouse,
  iconoreportes: LuChartColumn,
  iconoempresa: LuBuilding2,
  iconocategorias: LuLayoutGrid,
  iconomarca: LuTag,
  iconokardex: LuArrowLeftRight,
  iconoUser: LuUserRound,
  iconoUsuarios: LuUsers,
  iconoCerrarSesion: LuLogOut,
  iconoventas: LuShoppingCart,
  iconofacturas: LuReceiptText,
  iconobodegas: LuWarehouse,
  iconocompras: LuTruck,
  iconoclientes: LuContact,
  iconoproveedores: LuPackageCheck,
  iconoconfiguracion: LuSettings,
  icononotificaciones: LuBell,
  icononovandra: LuSparkles,
  iconoplan: LuCrown,
  iconointeligencia: LuBrain,
  iconoauditoria: LuScanEye,
  iconosucursales: LuMapPinned,
  // tipos de bodega
  iconotienda: LuStore,
  iconoonline: LuGlobe,
  iconosatelite: LuBox,
  // campos de formulario
  iconoprecioventa: LuBadgeDollarSign,
  iconopreciocompra: LuBanknote,
  iconocodigointerno: LuHash,
  iconocodigobarras: LuBarcode,
  iconostockminimo: LuTriangleAlert,
  iconostock: LuPackage,
  icononombre: LuTextCursorInput,
  iconoemail: LuMail,
  iconopass: LuLock,
  iconocalculadora: LuCalculator,
  iconotodos: LuInbox,
  iconotelefono: LuPhone,
  iconodireccion: LuMapPin,
  iconodocumento: LuIdCard,
  iconoporcentaje: LuPercent,
  iconofecha: LuCalendarClock,
  iconolista: LuClipboardList,
  // métodos de pago
  iconoefectivo: LuWallet,
  iconotarjeta: LuCreditCard,
  iconotransferencia: LuLandmark,
  iconocelular: LuSmartphone,
  // acciones
  agregar: LuPlus,
  quitar: LuMinus,
  iconoguardar: LuSave,
  iconocerrar: LuX,
  iconeditarTabla: LuPencil,
  iconeliminarTabla: LuTrash2,
  iconocheck: LuCircleCheck,
  iconolisto: LuCheck,
  iconodescargar: LuDownload,
  iconoimprimir: LuPrinter,
  iconoenviar: LuSend,
  iconoanular: LuBan,
  iconobuscar: LuSearch,
  iconodocumentoPdf: LuFileText,
  iconoilimitado: LuInfinity,
  iconorayo: LuZap,
  // flechas y tendencias
  iconoFlechabajo: LuChevronDown,
  iconoflechaderecha: LuChevronRight,
  flechaabajolarga: LuArrowDown,
  flechaarribalarga: LuArrowUp,
  iconoabrir: LuArrowUpRight,
  iconosube: LuTrendingUp,
  iconobaja: LuTrendingDown,
};
