-- =====================================================================
-- Stockly: complementos (capacidad adicional que se compra sobre el plan).
--
-- Una empresa con plan pagado vigente (Pro o Enterprise) puede comprar, por ejemplo,
-- usuarios, sedes o productos adicionales sin cambiar de plan. Reglas:
--  * Cada complemento suma una cantidad fija a uno o más límites del plan.
--  * Se cobra proporcional a los días que le quedan al plan y vence con él.
--  * Al renovar el mismo plan, los complementos vigentes se renuevan con él
--    (opcional), por el mismo ciclo (anual = 10 meses, como los planes).
--  * Tiene tope de unidades por empresa (nada ilimitado) y cuesta más por
--    unidad que lo que trae incluido el plan.
-- stockly_plan() devuelve el plan efectivo con los complementos sumados, así que
-- todos los topes del servidor (triggers, ventas, Novandra, invitaciones) los cuentan.
-- Requiere 20261020000000_limites_planes.sql. Se puede ejecutar varias veces.
-- =====================================================================

create table if not exists public.stockly_complementos (
  id text primary key,
  nombre text not null,
  descripcion text not null,
  incrementos jsonb not null,           -- por unidad, p. ej. {"limite_usuarios": 1}
  precio_mensual numeric(14, 2) not null,
  max_unidades int not null,            -- tope de unidades vigentes por empresa
  requiere text,                        -- ajuste global que debe estar activo (p. ej. novandra_ia_disponible)
  orden int not null default 0,
  activo boolean not null default true
);
alter table public.stockly_complementos enable row level security;
drop policy if exists "todos ven los complementos" on public.stockly_complementos;
create policy "todos ven los complementos" on public.stockly_complementos for select using (true);

insert into public.stockly_complementos (id, nombre, descripcion, incrementos, precio_mensual, max_unidades, requiere, orden) values
  ('usuario',   'Usuario adicional',        '1 persona más en tu equipo, con su propio acceso.',       '{"limite_usuarios": 1}',               14900, 30, null, 1),
  ('sede',      'Sede adicional',           '1 sede más, con 2 bodegas incluidas.',                    '{"limite_sucursales": 1, "limite_bodegas": 2}', 24900, 10, null, 2),
  ('bodegas',   '2 bodegas adicionales',    '2 bodegas más para separar tu inventario.',               '{"limite_bodegas": 2}',                9900, 15, null, 3),
  ('productos', '2.000 productos más',      'Amplía tu catálogo en 2.000 productos.',                  '{"limite_productos": 2000}',           14900, 25, null, 4),
  ('ventas',    '2.000 ventas más al mes',  '2.000 ventas adicionales cada mes.',                      '{"limite_ventas_mes": 2000}',          19900, 25, null, 5),
  ('clientes',  '5.000 clientes más',       '5.000 clientes y 200 proveedores adicionales.',           '{"limite_clientes": 5000, "limite_proveedores": 200}', 9900, 10, null, 6),
  ('archivos',  '5 GB de archivos',         '5 GB más para facturas de proveedores y documentos.',     '{"limite_archivos_mb": 5120}',         9900, 10, null, 7),
  ('informes',  '10 envíos al contador',    '10 envíos más del informe contable cada mes.',            '{"limite_informes_mes": 10}',          4900, 10, null, 8),
  ('novandra',  '50 consultas a Novandra Max', '50 consultas más al mes a tu agente de IA completo.',       '{"limite_novandra_mes": 50, "presupuesto_ia_cop": 12000}', 19900, 10, 'novandra_ia_disponible', 9)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, incrementos = excluded.incrementos,
  precio_mensual = excluded.precio_mensual, max_unidades = excluded.max_unidades,
  requiere = excluded.requiere, orden = excluded.orden;

-- Complementos comprados: cada compra (o renovación) es una fila con su vigencia.
create table if not exists public.empresa_complementos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_complemento text not null references public.stockly_complementos(id),
  cantidad int not null check (cantidad > 0),
  desde timestamptz not null default now(),
  hasta timestamptz not null,
  id_pago bigint,
  created_at timestamptz not null default now()
);
create index if not exists empresa_complementos_vigentes on public.empresa_complementos (id_empresa, hasta);
alter table public.empresa_complementos enable row level security;
drop policy if exists "miembros ven sus complementos" on public.empresa_complementos;
create policy "miembros ven sus complementos" on public.empresa_complementos for select using (public.stockly_es_miembro(id_empresa));

-- Pagos: además de planes, compras de complementos.
alter table public.pagos_suscripcion add column if not exists tipo text not null default 'plan';
alter table public.pagos_suscripcion add column if not exists complementos jsonb;   -- [{id, cantidad, total}]
alter table public.pagos_suscripcion drop constraint if exists pagos_suscripcion_tipo_check;
alter table public.pagos_suscripcion add constraint pagos_suscripcion_tipo_check check (tipo in ('plan', 'complemento'));

-- Unidades vigentes de cada complemento en una fecha.
create or replace function public.stockly_complementos_vigentes(_id_empresa bigint, _en timestamptz default now())
returns table (id_complemento text, cantidad bigint)
language sql stable security definer set search_path = public
as $$
  select ec.id_complemento, sum(ec.cantidad)
    from empresa_complementos ec
   where ec.id_empresa = _id_empresa and ec.desde <= _en and ec.hasta > _en
   group by ec.id_complemento
$$;
revoke execute on function public.stockly_complementos_vigentes(bigint, timestamptz) from public, anon;

-- --------------------------------------------------------------- Plan efectivo + complementos
create or replace function public.stockly_plan(_id_empresa bigint)
returns public.stockly_planes
language plpgsql stable security definer set search_path = public
as $$
declare
  _s public.stockly_suscripciones;
  _p public.stockly_planes;
  _extra jsonb;
begin
  select * into _s from stockly_suscripciones where id_empresa = _id_empresa;
  if _s.id_plan is not null and _s.id_plan <> 'basico' and _s.vence_en is not null and _s.vence_en > now() then
    select * into _p from stockly_planes where id = _s.id_plan;
  elsif _s.prueba_hasta is not null and _s.prueba_hasta > now() then
    select * into _p from stockly_planes where id = 'empresa';
    _p.limite_novandra_mes := 20;
    _p.presupuesto_ia_cop := 5000;
    _p.nombre := 'Enterprise (prueba)';
  else
    select * into _p from stockly_planes where id = 'basico';
  end if;

  -- Suma de los complementos vigentes: {"limite_usuarios": 3, ...}
  select jsonb_object_agg(k, total) into _extra
    from (select inc.key k, sum((inc.value)::numeric * v.cantidad) total
            from public.stockly_complementos_vigentes(_id_empresa) v
            join stockly_complementos c on c.id = v.id_complemento
            cross join lateral jsonb_each(c.incrementos) inc
           group by inc.key) t;
  if _extra is not null then
    select jsonb_object_agg(k, coalesce((to_jsonb(_p) ->> k)::numeric, 0) + (_extra ->> k)::numeric) into _extra
      from jsonb_object_keys(_extra) k;
    _p := jsonb_populate_record(_p, to_jsonb(_p) || _extra);
  end if;
  return _p;
end $$;

-- Complementos vigentes de la empresa (para la pantalla del plan).
create or replace function public.stockly_mis_complementos(_id_empresa bigint)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', c.id, 'nombre', c.nombre, 'cantidad', t.cantidad, 'hasta', t.hasta) order by c.orden)
      from (select id_complemento, sum(cantidad) cantidad, max(hasta) hasta
              from empresa_complementos
             where id_empresa = _id_empresa and desde <= now() and hasta > now()
             group by id_complemento) t
      join stockly_complementos c on c.id = t.id_complemento), '[]'::jsonb);
end $$;
grant execute on function public.stockly_mis_complementos(bigint) to authenticated;

-- --------------------------------------------------------------- Cotizar un complemento
-- Precio proporcional a los días que le quedan al plan (mínimo $3.000), vence con el plan.
create or replace function public.stockly_cotizar_complemento(_id_empresa bigint, _id_complemento text, _cantidad int)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  _c public.stockly_complementos;
  _s public.stockly_suscripciones;
  _vigentes bigint;
  _dias numeric;
  _total numeric;
begin
  if not public.stockly_es_admin(_id_empresa) then raise exception 'Solo el dueño o un administrador puede comprar complementos'; end if;
  select * into _c from stockly_complementos where id = _id_complemento and activo;
  if not found then raise exception 'Complemento no válido'; end if;
  if _c.requiere is not null and coalesce((public.stockly_ajuste(_c.requiere))::text, 'false') <> 'true' then
    raise exception '% estará disponible muy pronto.', _c.nombre;
  end if;
  if _cantidad is null or _cantidad < 1 or _cantidad > _c.max_unidades then raise exception 'Cantidad no válida'; end if;

  select * into _s from stockly_suscripciones where id_empresa = _id_empresa;
  if _s.id_plan = 'basico' or _s.vence_en is null or _s.vence_en <= now() then
    raise exception 'Los complementos están disponibles con un plan Pro o Enterprise pagado.';
  end if;
  if _s.vence_en < now() + interval '1 day' then
    raise exception 'Tu plan vence en menos de un día. Renuévalo primero y luego agrega complementos.';
  end if;

  select coalesce(sum(cantidad), 0) into _vigentes from public.stockly_complementos_vigentes(_id_empresa) where id_complemento = _id_complemento;
  if _vigentes + _cantidad > _c.max_unidades then
    raise exception 'Puedes tener hasta % unidades de "%". Ya tienes %.', _c.max_unidades, _c.nombre, _vigentes;
  end if;

  _dias := ceil(extract(epoch from _s.vence_en - now()) / 86400);
  _total := greatest(3000, round(_c.precio_mensual * _cantidad * _dias / 30 / 100) * 100);
  return jsonb_build_object('id', _c.id, 'nombre', _c.nombre, 'cantidad', _cantidad, 'precio_mensual', _c.precio_mensual,
                            'dias', _dias, 'hasta', _s.vence_en, 'total', _total, 'plan', _s.id_plan, 'ciclo', _s.ciclo);
end $$;
grant execute on function public.stockly_cotizar_complemento(bigint, text, int) to authenticated;

-- --------------------------------------------------------------- Cotizar el plan (+ complementos al renovar)
drop function if exists public.stockly_cotizar_plan(bigint, text, text);
create or replace function public.stockly_cotizar_plan(_id_empresa bigint, _id_plan text, _ciclo text, _con_complementos boolean default true)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  _p public.stockly_planes;
  _s public.stockly_suscripciones;
  _actual public.stockly_planes;
  _precio numeric;
  _pct int;
  _primera boolean;
  _descuento numeric := 0;
  _dias_renovar constant int := 7;
  _complementos jsonb := '[]'::jsonb;
  _total_complementos numeric := 0;
begin
  if not public.stockly_es_admin(_id_empresa) then raise exception 'Solo el dueño o un administrador puede comprar un plan'; end if;
  select * into _p from stockly_planes where id = _id_plan;
  if not found or _id_plan = 'basico' then raise exception 'Plan no válido'; end if;
  if _ciclo not in ('mensual', 'anual') then raise exception 'Ciclo no válido'; end if;

  select * into _s from stockly_suscripciones where id_empresa = _id_empresa;
  if _s.id_plan <> 'basico' and _s.vence_en is not null and _s.vence_en > now() then
    select * into _actual from stockly_planes where id = _s.id_plan;
    -- Pasar del mismo plan mensual a anual sí se permite en cualquier momento: el año se suma.
    if _s.id_plan = _id_plan and not (_s.ciclo = 'mensual' and _ciclo = 'anual')
       and _s.vence_en > now() + make_interval(days => _dias_renovar) then
      raise exception 'Tu plan % está pagado hasta el %. Podrás renovarlo desde el %.',
        _actual.nombre, to_char(_s.vence_en at time zone 'America/Bogota', 'DD/MM/YYYY'),
        to_char((_s.vence_en - make_interval(days => _dias_renovar)) at time zone 'America/Bogota', 'DD/MM/YYYY');
    end if;
    if _s.id_plan <> _id_plan and _p.orden < _actual.orden then
      raise exception 'Tu plan % está pagado hasta el %. Podrás cambiar a % cuando venza.',
        _actual.nombre, to_char(_s.vence_en at time zone 'America/Bogota', 'DD/MM/YYYY'), _p.nombre;
    end if;

    -- Renovación del mismo plan: los complementos vigentes al vencer se renuevan con él.
    if _s.id_plan = _id_plan and _con_complementos then
      select coalesce(jsonb_agg(jsonb_build_object('id', c.id, 'nombre', c.nombre, 'cantidad', v.cantidad,
                                                   'total', c.precio_mensual * v.cantidad * case when _ciclo = 'anual' then 10 else 1 end)
                                order by c.orden), '[]'::jsonb),
             coalesce(sum(c.precio_mensual * v.cantidad * case when _ciclo = 'anual' then 10 else 1 end), 0)
        into _complementos, _total_complementos
        from public.stockly_complementos_vigentes(_id_empresa, _s.vence_en - interval '1 second') v
        join stockly_complementos c on c.id = v.id_complemento;
    end if;
  end if;

  _precio := case when _ciclo = 'anual' then _p.precio_anual else _p.precio_mensual end;
  _primera := not exists (select 1 from pagos_suscripcion where id_empresa = _id_empresa and estado = 'aprobado');
  _pct := coalesce((public.stockly_ajuste('descuento_primera_compra'))::text::int, 0);
  -- El descuento de la primera compra es solo sobre el plan.
  if _primera and _pct > 0 then _descuento := round(_precio * _pct / 100.0); end if;
  return jsonb_build_object('plan', _p.id, 'nombre', _p.nombre, 'ciclo', _ciclo, 'precio', _precio,
                            'descuento', _descuento, 'descuento_pct', case when _descuento > 0 then _pct else 0 end,
                            'complementos', _complementos, 'total_complementos', _total_complementos,
                            'total', _precio - _descuento + _total_complementos, 'primera_compra', _primera);
end $$;
grant execute on function public.stockly_cotizar_plan(bigint, text, text, boolean) to authenticated;

-- --------------------------------------------------------------- Aplicar pagos (planes y complementos)
create or replace function public.stockly_aplicar_pago_suscripcion(
  _referencia text, _estado text, _transaccion text, _monto_centavos bigint, _metodo text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _pago public.pagos_suscripcion;
  _s public.stockly_suscripciones;
  _desde timestamptz;
  _hasta timestamptz;
  _plan_nombre text;
  _item jsonb;
begin
  select * into _pago from pagos_suscripcion where referencia = _referencia for update;
  if not found then return jsonb_build_object('ok', false, 'motivo', 'referencia desconocida'); end if;
  if _pago.estado = 'aprobado' then return jsonb_build_object('ok', true, 'repetido', true); end if;

  if _estado <> 'APPROVED' then
    update pagos_suscripcion set estado = case when _estado in ('DECLINED', 'VOIDED') then 'rechazado' when _estado = 'ERROR' then 'error' else estado end,
                                 transaccion = coalesce(_transaccion, transaccion), metodo = coalesce(_metodo, metodo)
     where id = _pago.id;
    return jsonb_build_object('ok', true, 'estado', _estado);
  end if;
  if _monto_centavos is distinct from round(_pago.total * 100)::bigint then
    return jsonb_build_object('ok', false, 'motivo', 'monto distinto');
  end if;

  -- Complemento: vale desde hoy hasta la fecha cotizada (el vencimiento del plan).
  if _pago.tipo = 'complemento' then
    for _item in select * from jsonb_array_elements(coalesce(_pago.complementos, '[]'::jsonb)) loop
      insert into empresa_complementos (id_empresa, id_complemento, cantidad, desde, hasta, id_pago)
      values (_pago.id_empresa, _item->>'id', (_item->>'cantidad')::int, now(), _pago.periodo_hasta, _pago.id);
    end loop;
    update pagos_suscripcion set estado = 'aprobado', transaccion = _transaccion, metodo = _metodo, aprobado_en = now()
     where id = _pago.id;
    insert into notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
    values (_pago.id_empresa, 'plan', 'Complemento activo',
            (select string_agg((i->>'cantidad') || ' × ' || c.nombre, ', ')
               from jsonb_array_elements(_pago.complementos) i join stockly_complementos c on c.id = i->>'id')
            || '. Vigente hasta el ' || to_char(_pago.periodo_hasta at time zone 'America/Bogota', 'DD/MM/YYYY') || '.',
            '/configurar/plan');
    return jsonb_build_object('ok', true, 'vence_en', _pago.periodo_hasta);
  end if;

  select * into _s from stockly_suscripciones where id_empresa = _pago.id_empresa for update;
  -- Si renueva el mismo plan antes de vencer, se suma al tiempo que le queda; si cambia de plan, arranca hoy.
  _desde := case when _s.id_plan = _pago.id_plan and _s.vence_en > now() then _s.vence_en else now() end;
  _hasta := _desde + case when _pago.ciclo = 'anual' then interval '1 year' else interval '1 month' end;

  update stockly_suscripciones
     set id_plan = _pago.id_plan, ciclo = _pago.ciclo, estado = 'activa', vence_en = _hasta, renovacion = _hasta,
         inicio = case when id_plan = _pago.id_plan then inicio else now() end
   where id_empresa = _pago.id_empresa;
  update pagos_suscripcion set estado = 'aprobado', transaccion = _transaccion, metodo = _metodo,
                               aprobado_en = now(), periodo_hasta = _hasta
   where id = _pago.id;
  -- Complementos renovados junto con el plan: rigen en el nuevo periodo.
  for _item in select * from jsonb_array_elements(coalesce(_pago.complementos, '[]'::jsonb)) loop
    insert into empresa_complementos (id_empresa, id_complemento, cantidad, desde, hasta, id_pago)
    values (_pago.id_empresa, _item->>'id', (_item->>'cantidad')::int, _desde, _hasta, _pago.id);
  end loop;
  insert into historial_suscripcion (id_empresa, plan_anterior, plan_nuevo, ciclo, id_usuario)
  values (_pago.id_empresa, _s.id_plan, _pago.id_plan, _pago.ciclo, _pago.creado_por);

  select nombre into _plan_nombre from stockly_planes where id = _pago.id_plan;
  insert into notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
  values (_pago.id_empresa, 'plan', 'Pago recibido: plan ' || _plan_nombre,
          'Tu plan está activo hasta el ' || to_char(_hasta at time zone 'America/Bogota', 'DD/MM/YYYY') || '. ¡Gracias!',
          '/configurar/plan');
  return jsonb_build_object('ok', true, 'vence_en', _hasta);
end $$;
revoke execute on function public.stockly_aplicar_pago_suscripcion(text, text, text, bigint, text) from public, anon, authenticated;

-- Estado de un pago (para la pantalla de regreso desde Wompi).
create or replace function public.stockly_estado_pago_suscripcion(_referencia text)
returns jsonb
language sql stable security definer set search_path = public
as $$
  select jsonb_build_object('estado', p.estado, 'tipo', p.tipo, 'plan', pl.nombre, 'ciclo', p.ciclo, 'total', p.total,
                            'periodo_hasta', p.periodo_hasta, 'complementos', p.complementos)
    from pagos_suscripcion p join stockly_planes pl on pl.id = p.id_plan
   where p.referencia = _referencia and public.stockly_es_admin(p.id_empresa)
$$;
grant execute on function public.stockly_estado_pago_suscripcion(text) to authenticated;

-- Los mensajes de tope sugieren los complementos.
create or replace function public.tg_limite_plan()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  _plan public.stockly_planes := public.stockly_plan(new.id_empresa);
  _limite int;
  _usado bigint;
  _que text;
begin
  case tg_table_name
    when 'productos' then
      _limite := _plan.limite_productos; _que := 'productos';
      select count(*) into _usado from productos where id_empresa = new.id_empresa;
    when 'clientes' then
      _limite := _plan.limite_clientes; _que := 'clientes';
      select count(*) into _usado from clientes where id_empresa = new.id_empresa;
    when 'proveedores' then
      _limite := _plan.limite_proveedores; _que := 'proveedores';
      select count(*) into _usado from proveedores where id_empresa = new.id_empresa;
    when 'asignarempresa' then
      _limite := _plan.limite_usuarios; _que := 'usuarios';
      select count(*) into _usado from asignarempresa where id_empresa = new.id_empresa;
  end case;
  if _limite is not null and _usado >= _limite then
    raise exception 'Tu plan % permite hasta % %. Agrega un complemento o mejora tu plan en Plan y suscripción.', _plan.nombre, _limite, _que
      using errcode = 'P0001';
  end if;
  return new;
end $$;
