-- =====================================================================
-- Stockly v3.6: Novandra esencial (sin API externa) y Novandra Max (IA).
--
--  * Plan Básico: Novandra esencial, que funciona en la app sin costo de API:
--    entiende preguntas frecuentes, consulta los datos y aprende el
--    vocabulario y los patrones de cada empresa.
--  * Planes Pro y Empresa: Novandra Max (IA). Si la IA no está disponible,
--    responde el modo esencial.
--  * novandra_aprendizaje: frases de cada empresa y lo que significan (se
--    guardan cuando el usuario aclara una pregunta).
--  * stockly_patrones: ritmo del negocio (días y horas fuertes, productos que
--    se venden juntos, ticket promedio y clientes recurrentes).
-- Requiere 20261005000000_inteligencia.sql.
-- =====================================================================

-- Qué planes incluyen la IA.
alter table public.stockly_planes add column if not exists novandra_ia boolean not null default false;
update public.stockly_planes set novandra_ia = (id in ('pro', 'empresa'));
-- El modo esencial no consume consultas: el límite mensual aplica solo a Novandra Max.
update public.stockly_planes set limite_novandra_mes = 0 where id = 'basico';

-- ----------------------------------------------------------- Aprendizaje
create table if not exists public.novandra_aprendizaje (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  frase text not null,
  intencion text not null,
  usos int not null default 1,
  actualizado timestamptz not null default now(),
  unique (id_empresa, frase)
);
alter table public.novandra_aprendizaje enable row level security;
drop policy if exists "miembros leen aprendizaje" on public.novandra_aprendizaje;
create policy "miembros leen aprendizaje" on public.novandra_aprendizaje
  for select using (public.stockly_es_miembro(id_empresa));

-- Guarda (o refuerza) lo que significa una frase para la empresa.
create or replace function public.stockly_novandra_aprender(_id_empresa bigint, _frase text, _intencion text)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  _f text := left(btrim(regexp_replace(lower(coalesce(_frase, '')), '\s+', ' ', 'g')), 200);
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  if _f = '' or _intencion !~ '^[a-z_]{3,40}$' then return; end if;
  insert into novandra_aprendizaje (id_empresa, frase, intencion)
  values (_id_empresa, _f, _intencion)
  on conflict (id_empresa, frase) do update
    set intencion = excluded.intencion,
        usos = novandra_aprendizaje.usos + case when novandra_aprendizaje.intencion = excluded.intencion then 1 else 0 end,
        actualizado = now();
  -- Cada empresa guarda como máximo 500 frases (se descartan las menos usadas).
  delete from novandra_aprendizaje
   where id in (select id from novandra_aprendizaje where id_empresa = _id_empresa
                 order by usos desc, actualizado desc offset 500);
end $$;
grant execute on function public.stockly_novandra_aprender(bigint, text, text) to authenticated;

-- ----------------------------------------------------------- Patrones del negocio
create or replace function public.stockly_patrones(_id_empresa bigint, _dias int default 90, _id_sucursal bigint default null)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _desde timestamptz := now() - make_interval(days => greatest(least(coalesce(_dias, 90), 365), 7));
  _num_ventas int;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;

  drop table if exists _v;
  create temp table _v on commit drop as
    select v.id, v.total, v.id_cliente, (v.fecha at time zone 'America/Bogota') as local
      from ventas v
      left join bodegas b on b.id = v.id_bodega
     where v.id_empresa = _id_empresa and v.estado <> 'anulada' and v.fecha >= _desde
       and (_id_sucursal is null or b.id_sucursal = _id_sucursal);
  select count(*) into _num_ventas from _v;

  return jsonb_build_object(
    'dias', greatest(least(coalesce(_dias, 90), 365), 7),
    'ventas', _num_ventas,
    'ticket_promedio', (select round(avg(total)) from _v),
    'unidades_por_venta', (select round(avg(u), 1) from (
        select sum(d.cantidad) u from detalle_venta d join _v on _v.id = d.id_venta group by d.id_venta) t),
    -- 0 = domingo … 6 = sábado
    'por_dia_semana', coalesce((select jsonb_agg(jsonb_build_object('dia', dia, 'ventas', n, 'total', t) order by dia) from (
        select extract(dow from local)::int dia, count(*) n, sum(total) t from _v group by 1) x), '[]'),
    'por_hora', coalesce((select jsonb_agg(jsonb_build_object('hora', hora, 'ventas', n, 'total', t) order by hora) from (
        select extract(hour from local)::int hora, count(*) n, sum(total) t from _v group by 1) x), '[]'),
    -- Productos que se compran juntos: veces, confianza (A→B) y lift (>1 = más de lo esperado por azar).
    'combos', coalesce((select jsonb_agg(c order by (c->>'veces')::int desc, (c->>'lift')::numeric desc) from (
        select jsonb_build_object(
                 'a', pa.descripcion, 'b', pb.descripcion, 'veces', par.n,
                 'confianza', round(par.n::numeric / na.n, 2),
                 'lift', round((par.n::numeric * _num_ventas) / (na.n * nb.n), 2)) c
          from (select d1.id_producto a, d2.id_producto b, count(distinct d1.id_venta) n
                  from detalle_venta d1
                  join detalle_venta d2 on d2.id_venta = d1.id_venta and d2.id_producto > d1.id_producto
                  join _v on _v.id = d1.id_venta
                 group by 1, 2 having count(distinct d1.id_venta) >= 2) par
          join (select d.id_producto, count(distinct d.id_venta) n from detalle_venta d join _v on _v.id = d.id_venta group by 1) na on na.id_producto = par.a
          join (select d.id_producto, count(distinct d.id_venta) n from detalle_venta d join _v on _v.id = d.id_venta group by 1) nb on nb.id_producto = par.b
          join productos pa on pa.id = par.a
          join productos pb on pb.id = par.b
         order by par.n desc limit 10) t), '[]'),
    'clientes', jsonb_build_object(
        'con_compra', (select count(distinct id_cliente) from _v where id_cliente is not null),
        'recurrentes', (select count(*) from (select id_cliente from _v where id_cliente is not null group by 1 having count(*) > 1) r),
        'ventas_sin_cliente', (select count(*) from _v where id_cliente is null),
        'top', coalesce((select jsonb_agg(jsonb_build_object('nombre', c.nombre, 'compras', x.n, 'total', x.t) order by x.t desc) from (
            select id_cliente, count(*) n, sum(total) t from _v where id_cliente is not null group by 1 order by 3 desc limit 5) x
            join clientes c on c.id = x.id_cliente), '[]'))
  );
end $$;
grant execute on function public.stockly_patrones(bigint, int, bigint) to authenticated;
