-- =====================================================================
-- Stockly: correo de recuperar contraseña enviado por Stockly (Brevo API).
--
-- La Edge Function recuperar-contrasena genera el enlace seguro de Supabase y lo
-- envía con la plantilla de Stockly, igual que los demás correos. Esta tabla
-- registra las solicitudes para limitar abusos (por correo y por IP).
-- Solo la usa la función (llave de servicio). Se puede ejecutar varias veces.
-- =====================================================================

create table if not exists public.recuperaciones_contrasena (
  id bigint generated by default as identity primary key,
  email text not null,
  ip text,
  created_at timestamptz not null default now()
);
create index if not exists recuperaciones_contrasena_email on public.recuperaciones_contrasena (email, created_at desc);
create index if not exists recuperaciones_contrasena_ip on public.recuperaciones_contrasena (ip, created_at desc);
alter table public.recuperaciones_contrasena enable row level security;
revoke all on public.recuperaciones_contrasena from anon, authenticated;
