-- =====================================================================
-- Stockly v3.9: solicitudes de soporte desde la app.
--
-- La persona escribe desde el panel de Soporte; la solicitud se guarda aquí
-- (con número) y la Edge Function "soporte" la envía por correo al equipo de
-- Stockly y una confirmación a quien escribió.
-- =====================================================================

create table if not exists public.soporte_solicitudes (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_usuario bigint,
  nombre text,
  email text,
  categoria text not null check (categoria in ('duda', 'error', 'pagos', 'sugerencia', 'otro')),
  asunto text not null,
  mensaje text not null,
  contexto jsonb not null default '{}'::jsonb,  -- plan, pantalla, navegador
  estado text not null default 'abierta' check (estado in ('abierta', 'respondida', 'cerrada')),
  correo_enviado boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists soporte_solicitudes_empresa on public.soporte_solicitudes (id_empresa, created_at desc);

alter table public.soporte_solicitudes enable row level security;
-- Cada persona ve las solicitudes de su empresa; nadie las edita desde la app.
drop policy if exists "miembros ven sus solicitudes" on public.soporte_solicitudes;
create policy "miembros ven sus solicitudes" on public.soporte_solicitudes
  for select using (public.stockly_es_miembro(id_empresa));

create or replace function public.crear_solicitud_soporte(
  _id_empresa bigint, _categoria text, _asunto text, _mensaje text, _contexto jsonb default '{}'::jsonb)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  _usuario bigint := public.stockly_id_usuario();
  _id bigint;
  _recientes int;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  if length(btrim(coalesce(_asunto, ''))) < 3 then raise exception 'Escribe un asunto'; end if;
  if length(btrim(coalesce(_mensaje, ''))) < 10 then raise exception 'Cuéntanos un poco más (mínimo 10 caracteres)'; end if;
  -- Límite anti abuso: 10 solicitudes por persona cada hora.
  select count(*) into _recientes from soporte_solicitudes
   where id_usuario is not distinct from _usuario and created_at > now() - interval '1 hour';
  if _recientes >= 10 then raise exception 'Enviaste muchas solicitudes seguidas. Intenta de nuevo en un rato.'; end if;

  insert into soporte_solicitudes (id_empresa, id_usuario, nombre, email, categoria, asunto, mensaje, contexto)
  values (_id_empresa, _usuario,
          (select nombres from "Usuarios" where id = _usuario),
          (select email from auth.users where id = auth.uid()),
          coalesce(nullif(_categoria, ''), 'otro'), left(btrim(_asunto), 150), left(btrim(_mensaje), 5000),
          coalesce(_contexto, '{}'::jsonb))
  returning id into _id;
  return _id;
end $$;
grant execute on function public.crear_solicitud_soporte(bigint, text, text, text, jsonb) to authenticated;
