-- =====================================================================
-- Stockly v3.1: medios de pago y links de pago con Wompi.
--
--  * pagos_venta: cada venta puede pagarse con uno o varios medios
--    (efectivo con cambio, datáfono con aprobación, transferencia, Nequi,
--    Daviplata, link de pago Wompi, crédito).
--  * Datos bancarios en la configuración de facturación.
--  * Credenciales de Wompi en una tabla que la app no puede leer: solo las
--    usan las Edge Functions (wompi-link y wompi-webhook).
--  * registrar_pago: abonos posteriores (crédito, transferencias que llegan después).
-- Requiere las migraciones anteriores.
-- =====================================================================

-- Métodos de pago permitidos en la venta ("mixto" cuando se paga con varios).
do $$
declare _c record;
begin
  for _c in
    select conname from pg_constraint
     where conrelid = 'public.ventas'::regclass and contype = 'c' and pg_get_constraintdef(oid) ilike '%metodo_pago%'
  loop
    execute format('alter table public.ventas drop constraint %I', _c.conname);
  end loop;
end $$;
alter table public.ventas add constraint ventas_metodo_pago_check check (metodo_pago in
  ('efectivo', 'tarjeta', 'datafono', 'transferencia', 'nequi', 'daviplata', 'link_pago', 'credito', 'mixto'));

create table if not exists public.pagos_venta (
  id bigint generated by default as identity primary key,
  id_venta bigint not null references public.ventas(id) on delete cascade,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  metodo text not null check (metodo in ('efectivo', 'tarjeta', 'datafono', 'transferencia', 'nequi', 'daviplata', 'link_pago', 'credito')),
  monto numeric(14, 2) not null check (monto > 0),
  recibido numeric(14, 2),          -- efectivo entregado por el cliente
  cambio numeric(14, 2),
  referencia text,                  -- n.º de aprobación del datáfono, referencia de la transferencia o id de Wompi
  franquicia text,                  -- Visa, Mastercard...
  banco text,
  estado text not null default 'aprobado' check (estado in ('aprobado', 'pendiente', 'rechazado', 'anulado')),
  link_id text,
  link_url text,
  id_usuario bigint,
  created_at timestamptz not null default now(),
  confirmado_en timestamptz
);
create index if not exists pagos_venta_venta on public.pagos_venta (id_venta);
create unique index if not exists pagos_venta_link on public.pagos_venta (link_id) where link_id is not null;

alter table public.pagos_venta enable row level security;
drop policy if exists "miembros ven pagos" on public.pagos_venta;
create policy "miembros ven pagos" on public.pagos_venta for select using (public.stockly_es_miembro(id_empresa));
-- Los pagos solo se crean o cambian desde las funciones (registrar_venta, registrar_pago, Wompi).

-- Pagos de las ventas que ya existían: uno por venta con su método.
insert into public.pagos_venta (id_venta, id_empresa, metodo, monto, estado, created_at)
select v.id, v.id_empresa, v.metodo_pago, v.total,
       case when v.estado = 'anulada' then 'anulado' when v.metodo_pago = 'credito' or v.estado = 'pendiente' then 'pendiente' else 'aprobado' end,
       v.fecha
  from public.ventas v
 where v.total > 0 and v.metodo_pago <> 'mixto'
   and not exists (select 1 from public.pagos_venta p where p.id_venta = v.id);

-- Datos bancarios (se imprimen en la factura y en el mensaje de WhatsApp) y Wompi.
alter table public.config_facturacion add column if not exists banco text;
alter table public.config_facturacion add column if not exists tipo_cuenta text;
alter table public.config_facturacion add column if not exists numero_cuenta text;
alter table public.config_facturacion add column if not exists titular_cuenta text;
alter table public.config_facturacion add column if not exists wompi_activo boolean not null default false;
alter table public.config_facturacion add column if not exists wompi_llave_publica text;

-- Llaves privadas: sin políticas, la app nunca las puede leer.
create table if not exists public.credenciales_pago (
  id_empresa bigint primary key references public."Empresa"(id) on delete cascade,
  wompi_llave_privada text,
  wompi_secreto_eventos text,
  updated_at timestamptz not null default now()
);
alter table public.credenciales_pago enable row level security;

create or replace function public.guardar_credenciales_wompi(_id_empresa bigint, _llave_privada text, _secreto_eventos text)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.stockly_es_admin(_id_empresa) then
    raise exception 'Solo el dueño o un administrador puede configurar Wompi';
  end if;
  if nullif(btrim(_llave_privada), '') is not null and btrim(_llave_privada) !~ '^prv_(test|prod)_' then
    raise exception 'La llave privada de Wompi debe empezar por prv_test_ o prv_prod_';
  end if;
  if nullif(btrim(_secreto_eventos), '') is not null and btrim(_secreto_eventos) !~ '^(test|prod)_events_' then
    raise exception 'El secreto de eventos debe empezar por test_events_ o prod_events_';
  end if;
  insert into credenciales_pago (id_empresa, wompi_llave_privada, wompi_secreto_eventos)
  values (_id_empresa, nullif(btrim(_llave_privada), ''), nullif(btrim(_secreto_eventos), ''))
  on conflict (id_empresa) do update set
    wompi_llave_privada = coalesce(excluded.wompi_llave_privada, credenciales_pago.wompi_llave_privada),
    wompi_secreto_eventos = coalesce(excluded.wompi_secreto_eventos, credenciales_pago.wompi_secreto_eventos),
    updated_at = now();
end $$;

-- Qué está configurado (sin revelar las llaves).
create or replace function public.estado_credenciales_wompi(_id_empresa bigint)
returns jsonb
language sql stable security definer set search_path = public
as $$
  select case when public.stockly_es_miembro(_id_empresa) then jsonb_build_object(
    'llave_privada', coalesce((select wompi_llave_privada is not null from credenciales_pago where id_empresa = _id_empresa), false),
    'secreto_eventos', coalesce((select wompi_secreto_eventos is not null from credenciales_pago where id_empresa = _id_empresa), false),
    'ambiente', (select case when wompi_llave_privada like 'prv_prod_%' then 'produccion'
                             when wompi_llave_privada like 'prv_test_%' then 'pruebas' end
                   from credenciales_pago where id_empresa = _id_empresa))
  end
$$;

-- ---------------------------------------------------------------------
-- registrar_venta con pagos
-- ---------------------------------------------------------------------
-- _venta: { id_empresa, id_bodega, id_cliente?, canal, metodo_pago?, nota?,
--           items: [{ id_producto, cantidad, precio_unitario, descuento?, iva? }],
--           pagos?: [{ metodo, monto, recibido?, referencia?, franquicia?, banco? }] }
-- Sin "pagos" se registra un solo pago por el total con "metodo_pago".
create or replace function public.registrar_venta(_venta jsonb)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _empresa bigint := (_venta->>'id_empresa')::bigint;
  _bodega bigint := (_venta->>'id_bodega')::bigint;
  _usuario bigint := public.stockly_id_usuario();
  _plan public.stockly_planes;
  _cfg public.config_facturacion;
  _item jsonb;
  _pago jsonb;
  _producto record;
  _cantidad numeric;
  _precio numeric;
  _desc numeric;
  _iva numeric;
  _base numeric;
  _subtotal numeric := 0;
  _descuento numeric := 0;
  _impuesto numeric := 0;
  _total numeric;
  _id_venta bigint;
  _numero int;
  _ventas_mes int;
  _pagos jsonb;
  _suma numeric := 0;
  _metodo text;
  _monto numeric;
  _recibido numeric;
  _cambio numeric := 0;
  _pendiente boolean := false;
  _metodos text[] := '{}';
begin
  if not public.stockly_es_miembro(_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  if not exists (select 1 from public.bodegas where id = _bodega and id_empresa = _empresa and activa) then
    raise exception 'Bodega no válida';
  end if;
  if jsonb_array_length(coalesce(_venta->'items', '[]'::jsonb)) = 0 then
    raise exception 'La venta no tiene productos';
  end if;

  _plan := public.stockly_plan(_empresa);
  if _plan.limite_ventas_mes is not null then
    _ventas_mes := (public.stockly_uso_plan(_empresa)->>'ventas_mes')::int;
    if _ventas_mes >= _plan.limite_ventas_mes then
      raise exception 'Llegaste al límite de % ventas del mes de tu plan %. Mejora tu plan para seguir vendiendo.',
        _plan.limite_ventas_mes, _plan.nombre;
    end if;
  end if;

  -- Consecutivo: bloquea la fila para que dos cajas no tomen el mismo número.
  select * into _cfg from public.config_facturacion where id_empresa = _empresa for update;
  if not found then
    perform public.stockly_inicializar_empresa(_empresa);
    select * into _cfg from public.config_facturacion where id_empresa = _empresa for update;
  end if;
  _numero := _cfg.consecutivo + 1;
  if _cfg.rango_hasta is not null and _numero > _cfg.rango_hasta then
    raise exception 'Se agotó el rango de numeración autorizado (%-%)', _cfg.rango_desde, _cfg.rango_hasta;
  end if;
  update public.config_facturacion set consecutivo = _numero, updated_at = now() where id_empresa = _empresa;

  insert into public.ventas (id_empresa, id_bodega, id_cliente, id_usuario, prefijo, numero, canal, metodo_pago, estado, nota)
  values (_empresa, _bodega, nullif(_venta->>'id_cliente', '')::bigint, _usuario, _cfg.prefijo, _numero,
          coalesce(_venta->>'canal', 'mostrador'), 'efectivo', 'pagada', _venta->>'nota')
  returning id into _id_venta;

  for _item in select * from jsonb_array_elements(_venta->'items') loop
    select id, descripcion into _producto from public.productos
     where id = (_item->>'id_producto')::bigint and id_empresa = _empresa;
    if not found then raise exception 'Producto no válido'; end if;

    _cantidad := (_item->>'cantidad')::numeric;
    _precio := (_item->>'precio_unitario')::numeric;
    _desc := coalesce((_item->>'descuento')::numeric, 0);
    _iva := coalesce((_item->>'iva')::numeric, 0);
    if _cantidad is null or _cantidad <= 0 then raise exception 'Cantidad no válida para %', _producto.descripcion; end if;
    if _precio is null or _precio < 0 or _desc < 0 or _iva < 0 then
      raise exception 'Precio o descuento no válido para %', _producto.descripcion;
    end if;
    if public.stockly_disponible(_bodega, _producto.id) < _cantidad then
      raise exception 'Stock insuficiente de % en esta bodega (disponible: %)',
        _producto.descripcion, trim_scale(public.stockly_disponible(_bodega, _producto.id));
    end if;

    _base := round(_cantidad * _precio - _desc, 2);
    if _base < 0 then raise exception 'El descuento de % supera el valor del producto', _producto.descripcion; end if;
    _subtotal := _subtotal + _cantidad * _precio;
    _descuento := _descuento + _desc;
    _impuesto := _impuesto + round(_base * _iva / 100, 2);

    insert into public.detalle_venta (id_venta, id_producto, descripcion, cantidad, precio_unitario, descuento, iva, total)
    values (_id_venta, _producto.id, _producto.descripcion, _cantidad, _precio, _desc, _iva,
            _base + round(_base * _iva / 100, 2));

    insert into public.kardex (fecha, tipo, id_usuario, cantidad, detalle, id_empresa, id_producto, id_bodega)
    values (now(), 'Salida', _usuario, _cantidad, 'Venta ' || _cfg.prefijo || '-' || _numero, _empresa, _producto.id, _bodega);
  end loop;

  _total := round(_subtotal - _descuento + _impuesto, 2);

  -- Pagos: si no vienen, uno solo por el total con el método indicado.
  _pagos := coalesce(nullif(_venta->'pagos', '[]'::jsonb),
                     jsonb_build_array(jsonb_build_object('metodo', coalesce(_venta->>'metodo_pago', 'efectivo'), 'monto', _total)));
  for _pago in select * from jsonb_array_elements(_pagos) loop
    _metodo := _pago->>'metodo';
    _monto := round((_pago->>'monto')::numeric, 2);
    _recibido := nullif(_pago->>'recibido', '')::numeric;
    if _metodo not in ('efectivo', 'tarjeta', 'datafono', 'transferencia', 'nequi', 'daviplata', 'link_pago', 'credito') then
      raise exception 'Medio de pago no válido: %', _metodo;
    end if;
    if _monto is null or _monto <= 0 then raise exception 'El valor de cada pago debe ser mayor que cero'; end if;
    if _metodo = 'efectivo' and _recibido is not null then
      if _recibido < _monto then raise exception 'El efectivo recibido es menor que el valor a pagar en efectivo'; end if;
      _cambio := _cambio + (_recibido - _monto);
    end if;
    if _metodo = 'datafono' and nullif(btrim(_pago->>'referencia'), '') is null then
      raise exception 'Escribe el número de aprobación del datáfono';
    end if;
    _pendiente := _pendiente or _metodo in ('link_pago', 'credito');
    _metodos := array_append(_metodos, _metodo);
    _suma := _suma + _monto;

    insert into public.pagos_venta (id_venta, id_empresa, metodo, monto, recibido, cambio, referencia, franquicia, banco, estado,
                                    id_usuario, confirmado_en)
    values (_id_venta, _empresa, _metodo, _monto, _recibido,
            case when _metodo = 'efectivo' and _recibido is not null then _recibido - _monto end,
            nullif(btrim(_pago->>'referencia'), ''), nullif(btrim(_pago->>'franquicia'), ''), nullif(btrim(_pago->>'banco'), ''),
            case when _metodo in ('link_pago', 'credito') then 'pendiente' else 'aprobado' end,
            _usuario, case when _metodo in ('link_pago', 'credito') then null else now() end);
  end loop;
  if abs(_suma - _total) > 1 then
    raise exception 'Los pagos (%) no suman el total de la venta (%)', trim_scale(_suma), trim_scale(_total);
  end if;

  update public.ventas
     set subtotal = round(_subtotal, 2), descuento = round(_descuento, 2), impuesto = round(_impuesto, 2), total = _total,
         metodo_pago = case when array_length(_metodos, 1) = 1 then _metodos[1] else 'mixto' end,
         estado = case when _pendiente then 'pendiente' else 'pagada' end
   where id = _id_venta;

  insert into public.facturas (id_venta, id_empresa, prefijo, numero, tipo, estado_dian)
  values (_id_venta, _empresa, _cfg.prefijo, _numero,
          case when _cfg.electronica_activa then 'electronica' else 'interna' end,
          case when _cfg.electronica_activa then 'pendiente' else 'no_aplica' end);

  insert into public.notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
  values (_empresa, 'venta', 'Nueva venta ' || _cfg.prefijo || '-' || _numero,
          jsonb_array_length(_venta->'items') || ' producto(s) · ' || coalesce(_venta->>'canal', 'mostrador'),
          '/ventas/facturas');

  return jsonb_build_object('id', _id_venta, 'prefijo', _cfg.prefijo, 'numero', _numero, 'total', _total,
                            'cambio', _cambio, 'pendiente', _pendiente,
                            'link_pago', 'link_pago' = any(_metodos));
end $$;

-- Abono a una venta pendiente (crédito, transferencia que llega después, efectivo).
create or replace function public.registrar_pago(_id_venta bigint, _pago jsonb)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _v public.ventas;
  _metodo text := _pago->>'metodo';
  _monto numeric := round((_pago->>'monto')::numeric, 2);
  _pagado numeric;
begin
  select * into _v from ventas where id = _id_venta for update;
  if not found or not public.stockly_es_miembro(_v.id_empresa) then raise exception 'Venta no encontrada'; end if;
  if _v.estado = 'anulada' then raise exception 'La venta está anulada'; end if;
  if _metodo not in ('efectivo', 'datafono', 'transferencia', 'nequi', 'daviplata') then
    raise exception 'Medio de pago no válido para un abono';
  end if;
  if _monto is null or _monto <= 0 then raise exception 'El valor debe ser mayor que cero'; end if;
  if _metodo = 'datafono' and nullif(btrim(_pago->>'referencia'), '') is null then
    raise exception 'Escribe el número de aprobación del datáfono';
  end if;

  select coalesce(sum(monto), 0) into _pagado from pagos_venta where id_venta = _id_venta and estado = 'aprobado';
  if _pagado + _monto > _v.total + 1 then
    raise exception 'El abono supera el saldo pendiente (%)', trim_scale(_v.total - _pagado);
  end if;

  insert into pagos_venta (id_venta, id_empresa, metodo, monto, referencia, franquicia, banco, estado, id_usuario, confirmado_en)
  values (_id_venta, _v.id_empresa, _metodo, _monto, nullif(btrim(_pago->>'referencia'), ''),
          nullif(btrim(_pago->>'franquicia'), ''), nullif(btrim(_pago->>'banco'), ''), 'aprobado', public.stockly_id_usuario(), now());

  _pagado := _pagado + _monto;
  if _pagado >= _v.total - 1 then
    update ventas set estado = 'pagada' where id = _id_venta;
    -- Lo que quedaba pendiente (crédito o link sin pagar) ya se cubrió.
    update pagos_venta set estado = 'anulado' where id_venta = _id_venta and estado = 'pendiente';
  end if;
  return jsonb_build_object('pagado', _pagado, 'saldo', greatest(_v.total - _pagado, 0), 'estado',
                            case when _pagado >= _v.total - 1 then 'pagada' else 'pendiente' end);
end $$;

-- Wompi confirma (o rechaza) el pago de un link. Solo la llama la Edge Function con la llave de servicio.
create or replace function public.stockly_confirmar_pago_link(_link_id text, _estado text, _transaccion text, _medio text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _p public.pagos_venta;
  _v public.ventas;
  _pagado numeric;
begin
  select * into _p from pagos_venta where link_id = _link_id for update;
  if not found then return jsonb_build_object('ok', false, 'motivo', 'link desconocido'); end if;
  if _p.estado = 'aprobado' then return jsonb_build_object('ok', true, 'repetido', true); end if;
  select * into _v from ventas where id = _p.id_venta;

  if _estado = 'APPROVED' then
    update pagos_venta set estado = 'aprobado', referencia = _transaccion, banco = _medio, confirmado_en = now() where id = _p.id;
    select coalesce(sum(monto), 0) into _pagado from pagos_venta where id_venta = _p.id_venta and estado = 'aprobado';
    if _pagado >= _v.total - 1 and _v.estado = 'pendiente' then
      update ventas set estado = 'pagada' where id = _p.id_venta;
    end if;
    insert into notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
    values (_p.id_empresa, 'venta', 'Pago recibido ' || _v.prefijo || '-' || _v.numero,
            'Wompi · ' || coalesce(_medio, 'tarjeta') || ' · ' || trim_scale(_p.monto), '/ventas/facturas');
  elsif _estado in ('DECLINED', 'ERROR', 'VOIDED') then
    update pagos_venta set referencia = _transaccion where id = _p.id;
    insert into notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
    values (_p.id_empresa, 'sistema', 'Pago rechazado ' || _v.prefijo || '-' || _v.numero,
            'El cliente intentó pagar con el link y la transacción no fue aprobada. El link sigue disponible.', '/ventas/facturas');
  end if;
  return jsonb_build_object('ok', true);
end $$;
revoke execute on function public.stockly_confirmar_pago_link(text, text, text, text) from public, anon, authenticated;

-- Al anular una venta, sus pagos quedan anulados.
create or replace function public.tg_ventas_anular_pagos()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.estado = 'anulada' and old.estado <> 'anulada' then
    update pagos_venta set estado = 'anulado' where id_venta = new.id;
  end if;
  return null;
end $$;
drop trigger if exists ventas_anular_pagos on public.ventas;
create trigger ventas_anular_pagos after update of estado on public.ventas
  for each row execute function public.tg_ventas_anular_pagos();

grant execute on function public.registrar_venta(jsonb), public.registrar_pago(bigint, jsonb),
  public.guardar_credenciales_wompi(bigint, text, text), public.estado_credenciales_wompi(bigint) to authenticated;
