-- =====================================================================
-- Stockly v3: sucursales, auditoría de movimientos, inteligencia de rotación
-- y permisos de Novandra.
--
--  * Sucursales: sedes que agrupan bodegas. Límite por plan.
--  * Auditoría: registro inalterable de quién hizo qué (ventas, anulaciones,
--    salidas manuales, movimientos borrados, cambios de precio y de stock,
--    traslados, órdenes). Solo lo ven el dueño y los administradores.
--  * Rotación: estadísticas por producto calculadas contra la propia empresa
--    (lo "normal" de cada negocio), pronóstico de demanda y alertas.
--  * novandra_config: lo que el dueño autoriza a Novandra.
-- Requiere las migraciones v2, registro y seguridad.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Sucursales
-- ---------------------------------------------------------------------
create table if not exists public.sucursales (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  nombre text not null,
  ciudad text,
  direccion text,
  telefono text,
  responsable text,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  unique (id_empresa, nombre)
);

alter table public.bodegas add column if not exists id_sucursal bigint references public.sucursales(id) on delete set null;
alter table public.stockly_planes add column if not exists limite_sucursales int;
update public.stockly_planes set limite_sucursales = case id when 'basico' then 1 when 'pro' then 3 else null end;

alter table public.sucursales enable row level security;
drop policy if exists "miembros sucursales" on public.sucursales;
create policy "miembros sucursales" on public.sucursales for select using (public.stockly_es_miembro(id_empresa));
drop policy if exists "admins sucursales" on public.sucursales;
create policy "admins sucursales" on public.sucursales for all
  using (public.stockly_es_admin(id_empresa)) with check (public.stockly_es_admin(id_empresa));

-- Cada empresa tiene una sede principal; sus bodegas sin sede quedan en ella.
create or replace function public.stockly_inicializar_sucursal(_id_empresa bigint)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare _id bigint;
begin
  select id into _id from sucursales where id_empresa = _id_empresa order by id limit 1;
  if _id is null then
    insert into sucursales (id_empresa, nombre, ciudad)
    select _id_empresa, 'Sede principal', e.ciudad from "Empresa" e where e.id = _id_empresa
    returning id into _id;
  end if;
  update bodegas set id_sucursal = _id where id_empresa = _id_empresa and id_sucursal is null;
  return _id;
end $$;

create or replace function public.tg_bodegas_sucursal()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.id_sucursal is null then
    new.id_sucursal := (select id from sucursales where id_empresa = new.id_empresa order by id limit 1);
  end if;
  return new;
end $$;
drop trigger if exists bodegas_sucursal on public.bodegas;
create trigger bodegas_sucursal before insert on public.bodegas
  for each row execute function public.tg_bodegas_sucursal();

create or replace function public.tg_empresa_sucursal()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.stockly_inicializar_sucursal(new.id);
  return new;
end $$;
-- Corre después de crear la bodega principal (orden alfabético de triggers: empresa_inicializar < empresa_sucursal).
drop trigger if exists empresa_sucursal on public."Empresa";
create trigger empresa_sucursal after insert on public."Empresa"
  for each row execute function public.tg_empresa_sucursal();

select public.stockly_inicializar_sucursal(id) from public."Empresa";

create or replace function public.tg_sucursales_limite()
returns trigger language plpgsql security definer set search_path = public
as $$
declare _limite int;
begin
  _limite := (public.stockly_plan(new.id_empresa)).limite_sucursales;
  if _limite is not null and (select count(*) from sucursales where id_empresa = new.id_empresa) >= _limite then
    raise exception 'Tu plan permite % sucursal(es). Mejora tu plan para agregar más.', _limite;
  end if;
  return new;
end $$;
drop trigger if exists sucursales_limite on public.sucursales;
create trigger sucursales_limite before insert on public.sucursales
  for each row execute function public.tg_sucursales_limite();

-- ---------------------------------------------------------------------
-- Auditoría (solo inserción, desde triggers)
-- ---------------------------------------------------------------------
create table if not exists public.auditoria (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_usuario bigint,            -- quién lo hizo realmente (usuario en sesión)
  usuario_nombre text,          -- nombre en ese momento
  accion text not null,
  entidad text not null,
  id_entidad bigint,
  id_producto bigint,
  id_bodega bigint references public.bodegas(id) on delete set null,
  id_sucursal bigint references public.sucursales(id) on delete set null,
  cantidad numeric,
  detalle jsonb not null default '{}'::jsonb,
  alerta text,                  -- motivo si el movimiento es sospechoso
  fecha timestamptz not null default now()
);
create index if not exists auditoria_empresa_fecha on public.auditoria (id_empresa, fecha desc);
create index if not exists auditoria_usuario on public.auditoria (id_empresa, id_usuario, fecha desc);

alter table public.auditoria enable row level security;
drop policy if exists "admins auditoria" on public.auditoria;
create policy "admins auditoria" on public.auditoria for select using (public.stockly_es_admin(id_empresa));
-- Sin políticas de insert/update/delete: nadie puede alterar el registro desde la app.

create or replace function public.stockly_auditar(
  _id_empresa bigint, _accion text, _entidad text, _id_entidad bigint, _detalle jsonb,
  _id_producto bigint default null, _id_bodega bigint default null, _cantidad numeric default null, _alerta text default null)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  _actor bigint := public.stockly_id_usuario();
  _hora int := extract(hour from now() at time zone 'America/Bogota');
begin
  if _id_empresa is null then return; end if;
  -- Fuera de horario (antes de 6 a. m. o desde las 10 p. m.) se marca para revisión.
  if _alerta is null and _actor is not null and (_hora < 6 or _hora >= 22) then
    _alerta := 'Fuera de horario';
  end if;
  insert into auditoria (id_empresa, id_usuario, usuario_nombre, accion, entidad, id_entidad, id_producto, id_bodega,
                         id_sucursal, cantidad, detalle, alerta)
  values (_id_empresa, _actor, (select nullif(nombres, '') from "Usuarios" where id = _actor), _accion, _entidad,
          _id_entidad, _id_producto, _id_bodega, (select id_sucursal from bodegas where id = _id_bodega), _cantidad,
          coalesce(_detalle, '{}'::jsonb), _alerta);
end $$;
revoke execute on function public.stockly_auditar(bigint, text, text, bigint, jsonb, bigint, bigint, numeric, text) from public, anon, authenticated;

-- Kardex: solo los movimientos manuales (los de ventas, anulaciones y compras se auditan en su origen).
create or replace function public.tg_auditar_kardex()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  _fila record;
  _actor bigint := public.stockly_id_usuario();
  _alerta text;
begin
  if tg_op = 'DELETE' then _fila := old; else _fila := new; end if;
  if tg_op = 'INSERT' and coalesce(_fila.detalle, '') ~ '^(Venta |Anulación |Orden de compra )' then
    return null;
  end if;
  if tg_op = 'INSERT' and _actor is not null and _fila.id_usuario is distinct from _actor then
    _alerta := 'Registrado a nombre de otro usuario';
  elsif tg_op = 'DELETE' then
    _alerta := 'Movimiento eliminado';
  end if;
  perform public.stockly_auditar(
    _fila.id_empresa,
    case when tg_op = 'DELETE' then 'movimiento_eliminado'
         when lower(_fila.tipo) = 'salida' then 'salida_manual' else 'entrada_manual' end,
    'kardex', _fila.id,
    jsonb_build_object('tipo', _fila.tipo, 'detalle', _fila.detalle, 'fecha_movimiento', _fila.fecha,
                       'usuario_declarado', _fila.id_usuario,
                       'producto', (select descripcion from productos where id = _fila.id_producto)),
    _fila.id_producto, _fila.id_bodega, _fila.cantidad, _alerta);
  return null;
end $$;
drop trigger if exists auditar_kardex on public.kardex;
create trigger auditar_kardex after insert or delete on public.kardex
  for each row execute function public.tg_auditar_kardex();

create or replace function public.tg_auditar_ventas()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.stockly_auditar(new.id_empresa, 'venta', 'ventas', new.id,
      jsonb_build_object('factura', new.prefijo || '-' || new.numero, 'metodo_pago', new.metodo_pago, 'canal', new.canal),
      null, new.id_bodega, null);
  elsif new.estado = 'anulada' and old.estado <> 'anulada' then
    perform public.stockly_auditar(new.id_empresa, 'venta_anulada', 'ventas', new.id,
      jsonb_build_object('factura', new.prefijo || '-' || new.numero, 'total', new.total, 'nota', new.nota,
                         'vendida_por', new.id_usuario,
                         'vendedor', (select nombres from "Usuarios" where id = new.id_usuario)),
      null, new.id_bodega, null, 'Venta anulada');
  elsif new.total is distinct from old.total and old.total > 0 then
    -- Totales de una venta ya cerrada (registrar_venta los calcula una sola vez).
    perform public.stockly_auditar(new.id_empresa, 'venta_modificada', 'ventas', new.id,
      jsonb_build_object('factura', new.prefijo || '-' || new.numero, 'total_antes', old.total, 'total_despues', new.total,
                         'descuento', new.descuento),
      null, new.id_bodega, null, 'Total de venta modificado');
  elsif new.total is distinct from old.total and old.total = 0 and new.subtotal > 0 and new.descuento / new.subtotal > 0.2 then
    perform public.stockly_auditar(new.id_empresa, 'descuento_alto', 'ventas', new.id,
      jsonb_build_object('factura', new.prefijo || '-' || new.numero, 'subtotal', new.subtotal, 'descuento', new.descuento,
                         'porcentaje', round(new.descuento / new.subtotal * 100)),
      null, new.id_bodega, null, 'Descuento mayor al 20%');
  end if;
  return null;
end $$;
drop trigger if exists auditar_ventas on public.ventas;
create trigger auditar_ventas after insert or update on public.ventas
  for each row execute function public.tg_auditar_ventas();

create or replace function public.tg_auditar_productos()
returns trigger language plpgsql security definer set search_path = public
as $$
declare _cambios jsonb := '{}'::jsonb;
begin
  if tg_op = 'INSERT' then
    perform public.stockly_auditar(new.id_empresa, 'producto_creado', 'productos', new.id,
      jsonb_build_object('producto', new.descripcion, 'stock_inicial', new.stock, 'precio', new.precioventa), new.id, null, new.stock);
  elsif tg_op = 'DELETE' then
    perform public.stockly_auditar(old.id_empresa, 'producto_eliminado', 'productos', old.id,
      jsonb_build_object('producto', old.descripcion, 'stock', old.stock), old.id, null, old.stock, 'Producto eliminado');
  else
    if new.precioventa is distinct from old.precioventa then
      _cambios := _cambios || jsonb_build_object('precio_venta', jsonb_build_array(old.precioventa, new.precioventa));
    end if;
    if new.preciocompra is distinct from old.preciocompra then
      _cambios := _cambios || jsonb_build_object('precio_compra', jsonb_build_array(old.preciocompra, new.preciocompra));
    end if;
    if new.stock_minimo is distinct from old.stock_minimo then
      _cambios := _cambios || jsonb_build_object('stock_minimo', jsonb_build_array(old.stock_minimo, new.stock_minimo));
    end if;
    if _cambios <> '{}'::jsonb then
      perform public.stockly_auditar(new.id_empresa, 'producto_editado', 'productos', new.id,
        _cambios || jsonb_build_object('producto', new.descripcion), new.id, null, null,
        case when _cambios ? 'precio_venta' then 'Cambio de precio' end);
    end if;
    -- El stock solo debe cambiar por el kardex (trigger). Un cambio directo es sospechoso.
    if new.stock is distinct from old.stock and pg_trigger_depth() = 1 then
      perform public.stockly_auditar(new.id_empresa, 'stock_modificado_directo', 'productos', new.id,
        jsonb_build_object('producto', new.descripcion, 'antes', old.stock, 'despues', new.stock),
        new.id, null, new.stock - old.stock, 'Stock cambiado sin movimiento de kardex');
    end if;
  end if;
  return null;
end $$;
drop trigger if exists auditar_productos on public.productos;
create trigger auditar_productos after insert or update or delete on public.productos
  for each row execute function public.tg_auditar_productos();

create or replace function public.tg_auditar_traslados()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.stockly_auditar(new.id_empresa, 'traslado', 'traslados', new.id,
    jsonb_build_object('producto', (select descripcion from productos where id = new.id_producto),
                       'origen', (select nombre from bodegas where id = new.id_origen),
                       'destino', (select nombre from bodegas where id = new.id_destino), 'nota', new.nota),
    new.id_producto, new.id_origen, new.cantidad);
  return null;
end $$;
drop trigger if exists auditar_traslados on public.traslados;
create trigger auditar_traslados after insert on public.traslados
  for each row execute function public.tg_auditar_traslados();

create or replace function public.tg_auditar_ordenes()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.stockly_auditar(new.id_empresa, 'orden_creada', 'ordenes_compra', new.id,
      jsonb_build_object('orden', 'OC-' || new.numero, 'creada_por', new.creada_por), null, new.id_bodega, null);
  elsif new.estado is distinct from old.estado then
    perform public.stockly_auditar(new.id_empresa, 'orden_' || new.estado, 'ordenes_compra', new.id,
      jsonb_build_object('orden', 'OC-' || new.numero, 'total', new.total), null, new.id_bodega, null);
  end if;
  return null;
end $$;
drop trigger if exists auditar_ordenes on public.ordenes_compra;
create trigger auditar_ordenes after insert or update on public.ordenes_compra
  for each row execute function public.tg_auditar_ordenes();

create or replace function public.tg_auditar_usuarios()
returns trigger language plpgsql security definer set search_path = public
as $$
declare _empresa bigint;
begin
  select id_empresa into _empresa from asignarempresa where id_usuario = coalesce(new.id, old.id) limit 1;
  _empresa := coalesce(_empresa, (select id_empresa from asignarempresa where id_usuario = public.stockly_id_usuario() limit 1));
  if tg_op = 'UPDATE' and new.tipouser is distinct from old.tipouser then
    perform public.stockly_auditar(_empresa, 'rol_cambiado', 'Usuarios', new.id,
      jsonb_build_object('usuario', new.nombres, 'antes', old.tipouser, 'despues', new.tipouser), null, null, null, 'Cambio de rol');
  elsif tg_op = 'DELETE' then
    perform public.stockly_auditar(_empresa, 'usuario_eliminado', 'Usuarios', old.id,
      jsonb_build_object('usuario', old.nombres, 'email', old.email));
  end if;
  return null;
end $$;
drop trigger if exists auditar_usuarios on public."Usuarios";
create trigger auditar_usuarios after update or delete on public."Usuarios"
  for each row execute function public.tg_auditar_usuarios();

-- Resumen por empleado con puntaje de riesgo, para el dueño o administradores.
create or replace function public.stockly_auditoria_resumen(_id_empresa bigint, _dias int default 30)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare _desde timestamptz := now() - make_interval(days => _dias);
begin
  if not public.stockly_es_admin(_id_empresa) then
    raise exception 'Solo el dueño o un administrador puede ver la auditoría';
  end if;
  return coalesce((
    select jsonb_agg(t order by t.riesgo desc, t.movimientos desc) from (
      select u.id as id_usuario, coalesce(nullif(u.nombres, ''), u.email) as nombre, u.tipouser,
             count(a.id) as movimientos,
             count(*) filter (where a.accion = 'venta') as ventas,
             count(*) filter (where a.accion = 'venta_anulada') as anulaciones,
             count(*) filter (where a.accion = 'salida_manual') as salidas_manuales,
             coalesce(sum(a.cantidad) filter (where a.accion = 'salida_manual'), 0) as unidades_salida_manual,
             count(*) filter (where a.accion = 'movimiento_eliminado') as eliminados,
             count(*) filter (where a.alerta = 'Registrado a nombre de otro usuario') as suplantaciones,
             count(*) filter (where a.alerta = 'Fuera de horario') as fuera_horario,
             count(*) filter (where a.accion = 'stock_modificado_directo') as stock_directo,
             count(*) filter (where a.accion = 'producto_editado' and a.detalle ? 'precio_venta') as cambios_precio,
             count(*) filter (where a.accion = 'descuento_alto') as descuentos_altos,
             count(*) filter (where a.alerta is not null) as alertas,
             max(a.fecha) as ultima_actividad,
             ( 5 * count(*) filter (where a.alerta = 'Registrado a nombre de otro usuario')
             + 4 * count(*) filter (where a.accion = 'stock_modificado_directo')
             + 3 * count(*) filter (where a.accion = 'movimiento_eliminado')
             + 2 * count(*) filter (where a.accion = 'venta_anulada')
             + 2 * count(*) filter (where a.accion = 'descuento_alto')
             + 1 * count(*) filter (where a.accion = 'salida_manual')
             + 1 * count(*) filter (where a.alerta = 'Fuera de horario')) as riesgo
        from asignarempresa ae
        join "Usuarios" u on u.id = ae.id_usuario
        left join auditoria a on a.id_usuario = u.id and a.id_empresa = _id_empresa and a.fecha >= _desde
       where ae.id_empresa = _id_empresa
       group by u.id, u.nombres, u.email, u.tipouser) t), '[]'::jsonb);
end $$;

-- ---------------------------------------------------------------------
-- Inteligencia de rotación
-- ---------------------------------------------------------------------
-- Para cada producto: velocidad, frecuencia, tendencia, intervalo típico entre ventas,
-- cobertura y pronóstico. Las clases (alta/media/baja) se calculan contra los demás
-- productos de la misma empresa: así "normal" depende del tipo de negocio.
create or replace function public.stockly_rotacion(_id_empresa bigint, _dias int default 90, _id_sucursal bigint default null)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  _hoy date := (now() at time zone 'America/Bogota')::date;
  _desde date := _hoy - (_dias - 1);
  _resultado jsonb;
  _perfil jsonb;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;

  -- Solo se cuentan los días con historia: un negocio nuevo no se mide contra días sin datos.
  _dias := greatest(7, least(_dias, _hoy - coalesce(
    (select min((fecha at time zone 'America/Bogota')::date) from ventas
      where id_empresa = _id_empresa and estado <> 'anulada'), _hoy) + 1));
  _desde := _hoy - (_dias - 1);

  with ventas_dia as (
    select dv.id_producto, (v.fecha at time zone 'America/Bogota')::date as dia, sum(dv.cantidad) as unidades
      from detalle_venta dv
      join ventas v on v.id = dv.id_venta
      left join bodegas b on b.id = v.id_bodega
     where v.id_empresa = _id_empresa and v.estado <> 'anulada'
       and v.fecha >= _desde::timestamp at time zone 'America/Bogota'
       and (_id_sucursal is null or b.id_sucursal = _id_sucursal)
     group by 1, 2
  ),
  stock as (
    select id_producto, sum(cantidad) as cantidad from v_stock_bodega
     where id_empresa = _id_empresa
       and (_id_sucursal is null or id_bodega in (select id from bodegas where id_sucursal = _id_sucursal))
     group by 1
  ),
  base as (
    select p.id, p.descripcion, c.descripcion as categoria, p.stock_minimo, p.precioventa, p.preciocompra,
           coalesce(s.cantidad, 0) as stock,
           coalesce(sum(vd.unidades), 0) as unidades,
           count(vd.dia) as dias_con_venta,
           coalesce(sum(vd.unidades) filter (where vd.dia > _hoy - 14), 0) as unidades_14,
           coalesce(sum(vd.unidades) filter (where vd.dia > _hoy - 28 and vd.dia <= _hoy - 14), 0) as unidades_14_previos,
           max(vd.dia) as ultima_venta,
           coalesce(stddev_pop(vd.unidades), 0) as desviacion
      from productos p
      left join categorias c on c.id = p.id_categoria
      left join stock s on s.id_producto = p.id
      left join ventas_dia vd on vd.id_producto = p.id
     where p.id_empresa = _id_empresa
     group by p.id, p.descripcion, c.descripcion, p.stock_minimo, p.precioventa, p.preciocompra, s.cantidad
  ),
  calculo as (
    select b.*,
           round(b.dias_con_venta::numeric / _dias, 3) as frecuencia,
           round(b.unidades::numeric / _dias, 3) as venta_diaria,
           -- Velocidad ponderada: pesa más lo reciente (aprende del cambio de ritmo).
           round(0.6 * (b.unidades_14::numeric / 14) + 0.4 * (b.unidades::numeric / _dias), 3) as velocidad,
           case when b.dias_con_venta > 0 then round(_dias::numeric / b.dias_con_venta, 1) end as intervalo_tipico,
           case when b.ultima_venta is not null then _hoy - b.ultima_venta end as dias_sin_venta,
           case when b.unidades_14_previos > 0
                then round((b.unidades_14 - b.unidades_14_previos) * 100.0 / b.unidades_14_previos)
                when b.unidades_14 > 0 then 100 end as tendencia
      from base b
  ),
  umbrales as (
    select percentile_cont(0.66) within group (order by frecuencia) as p66,
           percentile_cont(0.33) within group (order by frecuencia) as p33,
           percentile_cont(0.5) within group (order by frecuencia) as mediana
      from calculo where frecuencia > 0
  ),
  final as (
    select c.*,
           case when c.unidades = 0 then 'sin_movimiento'
                when c.frecuencia >= u.p66 then 'alta'
                when c.frecuencia >= u.p33 then 'media'
                else 'baja' end as rotacion,
           case when c.velocidad > 0 then round(c.stock / c.velocidad, 1) end as dias_cobertura,
           round(c.velocidad * 7, 1) as pronostico_7,
           round(c.velocidad * 30, 1) as pronostico_30,
           -- Reponer para cubrir 30 días + seguridad (la mitad de una semana de demanda + variabilidad).
           greatest(ceil(c.velocidad * 30 + c.velocidad * 3.5 + c.desviacion * 2 - c.stock), 0) as sugerido_reponer
      from calculo c cross join umbrales u
  )
  select jsonb_agg(jsonb_build_object(
           'id', f.id, 'descripcion', f.descripcion, 'categoria', f.categoria,
           'stock', f.stock, 'stock_minimo', f.stock_minimo, 'precioventa', f.precioventa, 'preciocompra', f.preciocompra,
           'unidades', f.unidades, 'dias_con_venta', f.dias_con_venta, 'frecuencia', f.frecuencia,
           'venta_diaria', f.venta_diaria, 'velocidad', f.velocidad, 'tendencia', f.tendencia,
           'intervalo_tipico', f.intervalo_tipico, 'dias_sin_venta', f.dias_sin_venta, 'ultima_venta', f.ultima_venta,
           'rotacion', f.rotacion, 'dias_cobertura', f.dias_cobertura,
           'fecha_agotamiento', case when f.dias_cobertura is not null then _hoy + floor(f.dias_cobertura)::int end,
           'pronostico_7', f.pronostico_7, 'pronostico_30', f.pronostico_30,
           'sugerido_reponer', case when f.rotacion = 'sin_movimiento' then 0 else f.sugerido_reponer end,
           'capital_inmovilizado', case when f.rotacion = 'sin_movimiento' then f.stock * coalesce(f.preciocompra, 0) else 0 end,
           'alerta', case
             when f.stock <= 0 and f.velocidad > 0 then 'agotado'
             when f.dias_cobertura is not null and f.dias_cobertura < 7 then 'agotamiento_proximo'
             when f.intervalo_tipico is not null and f.dias_con_venta >= 3
                  and f.dias_sin_venta > greatest(f.intervalo_tipico * 2.5, 3) then 'detenido'
             when f.rotacion = 'sin_movimiento' and f.stock > 0 then 'sin_movimiento'
             when f.dias_cobertura is not null and f.dias_cobertura > 120 then 'sobrestock'
           end
         ) order by f.velocidad desc, f.descripcion)
    into _resultado from final f;

  select jsonb_build_object(
           'dias_analizados', _dias,
           'productos', count(*),
           'frecuencia_mediana', (select mediana from (select percentile_cont(0.5) within group (order by (x->>'frecuencia')::numeric) as mediana
                                    from jsonb_array_elements(_resultado) x where (x->>'frecuencia')::numeric > 0) m),
           'dias_con_ventas', (select count(distinct (fecha at time zone 'America/Bogota')::date) from ventas
                                where id_empresa = _id_empresa and estado <> 'anulada'
                                  and fecha >= _desde::timestamp at time zone 'America/Bogota'),
           'dia_mas_fuerte', (select (array['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo'])
                                         [extract(isodow from fecha at time zone 'America/Bogota')::int]
                                from ventas
                               where id_empresa = _id_empresa and estado <> 'anulada'
                                 and fecha >= _desde::timestamp at time zone 'America/Bogota'
                               group by extract(isodow from fecha at time zone 'America/Bogota')
                               order by sum(total) desc limit 1))
    into _perfil from jsonb_array_elements(coalesce(_resultado, '[]'::jsonb));

  return jsonb_build_object('perfil', _perfil, 'productos', coalesce(_resultado, '[]'::jsonb));
end $$;

-- ---------------------------------------------------------------------
-- Dashboard con filtro por sucursal
-- ---------------------------------------------------------------------
drop function if exists public.stockly_dashboard(bigint, int);
create or replace function public.stockly_dashboard(_id_empresa bigint, _dias int default 30, _id_sucursal bigint default null)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  _hoy date := (now() at time zone 'America/Bogota')::date;
  _desde date := _hoy - (_dias - 1);
  _ventas jsonb;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;

  with dias as (select generate_series(_desde, _hoy, interval '1 day')::date as dia),
       v as (select (ve.fecha at time zone 'America/Bogota')::date as dia, ve.total
               from public.ventas ve left join public.bodegas b on b.id = ve.id_bodega
              where ve.id_empresa = _id_empresa and ve.estado <> 'anulada'
                and (_id_sucursal is null or b.id_sucursal = _id_sucursal)
                and ve.fecha >= (_desde - _dias)::timestamp at time zone 'America/Bogota')
  select jsonb_build_object(
    'serie', (select jsonb_agg(jsonb_build_object('fecha', d.dia,
                'total', coalesce((select sum(total) from v where v.dia = d.dia), 0),
                'ventas', (select count(*) from v where v.dia = d.dia)) order by d.dia) from dias d),
    'total_periodo', (select coalesce(sum(total), 0) from v where dia >= _desde),
    'total_anterior', (select coalesce(sum(total), 0) from v where dia < _desde),
    'num_ventas', (select count(*) from v where dia >= _desde),
    'total_hoy', (select coalesce(sum(total), 0) from v where dia = _hoy),
    'ventas_hoy', (select count(*) from v where dia = _hoy)
  ) into _ventas;

  return _ventas || jsonb_build_object(
    'top_productos', coalesce((
      select jsonb_agg(t) from (
        select dv.id_producto, dv.descripcion, sum(dv.cantidad) as cantidad, sum(dv.total) as total
          from public.detalle_venta dv join public.ventas ve on ve.id = dv.id_venta
          left join public.bodegas b on b.id = ve.id_bodega
         where ve.id_empresa = _id_empresa and ve.estado <> 'anulada'
           and (_id_sucursal is null or b.id_sucursal = _id_sucursal)
           and ve.fecha >= _desde::timestamp at time zone 'America/Bogota'
         group by dv.id_producto, dv.descripcion order by sum(dv.cantidad) desc limit 5) t), '[]'::jsonb),
    'por_metodo', coalesce((
      select jsonb_agg(t) from (
        select ve.metodo_pago as metodo, sum(ve.total) as total, count(*) as ventas
          from public.ventas ve left join public.bodegas b on b.id = ve.id_bodega
         where ve.id_empresa = _id_empresa and ve.estado <> 'anulada'
           and (_id_sucursal is null or b.id_sucursal = _id_sucursal)
           and ve.fecha >= _desde::timestamp at time zone 'America/Bogota'
         group by ve.metodo_pago order by sum(ve.total) desc) t), '[]'::jsonb),
    'por_sucursal', coalesce((
      select jsonb_agg(t order by t.total desc) from (
        select s.id, s.nombre, coalesce(sum(ve.total), 0) as total, count(ve.id) as ventas
          from public.sucursales s
          left join public.bodegas b on b.id_sucursal = s.id
          left join public.ventas ve on ve.id_bodega = b.id and ve.estado <> 'anulada'
                                    and ve.fecha >= _desde::timestamp at time zone 'America/Bogota'
         where s.id_empresa = _id_empresa and s.activa
         group by s.id, s.nombre) t), '[]'::jsonb),
    'bodegas', coalesce((
      select jsonb_agg(t order by t.tipo = 'principal' desc, t.nombre) from (
        select b.id, b.nombre, b.tipo, coalesce(sum(s.cantidad), 0) as unidades
          from public.bodegas b left join public.v_stock_bodega s on s.id_bodega = b.id
         where b.id_empresa = _id_empresa and b.activa
           and (_id_sucursal is null or b.id_sucursal = _id_sucursal)
         group by b.id, b.nombre, b.tipo) t), '[]'::jsonb),
    'recientes', coalesce((
      select jsonb_agg(t) from (
        select ve.id, ve.prefijo, ve.numero, ve.total, ve.estado, ve.fecha, ve.canal, c.nombre as cliente
          from public.ventas ve
          left join public.clientes c on c.id = ve.id_cliente
          left join public.bodegas b on b.id = ve.id_bodega
         where ve.id_empresa = _id_empresa and (_id_sucursal is null or b.id_sucursal = _id_sucursal)
         order by ve.fecha desc limit 5) t), '[]'::jsonb),
    'valor_inventario', (select coalesce(sum(stock * preciocompra), 0) from public.productos where id_empresa = _id_empresa),
    'valor_venta_inventario', (select coalesce(sum(stock * precioventa), 0) from public.productos where id_empresa = _id_empresa),
    'bajo_minimo', (select count(*) from public.productos where id_empresa = _id_empresa and stock <= coalesce(stock_minimo, 0)),
    'ordenes_abiertas', (select count(*) from public.ordenes_compra where id_empresa = _id_empresa and estado in ('borrador', 'enviada'))
  );
end $$;

-- ---------------------------------------------------------------------
-- Lo que el dueño autoriza a Novandra
-- ---------------------------------------------------------------------
create table if not exists public.novandra_config (
  id_empresa bigint primary key references public."Empresa"(id) on delete cascade,
  empleados_pueden_usar boolean not null default true,
  empleados_ven_costos boolean not null default false,
  puede_crear_ordenes boolean not null default true,
  puede_crear_recordatorios boolean not null default true,
  auditoria_activa boolean not null default true,
  instrucciones text,
  updated_at timestamptz not null default now()
);
alter table public.novandra_config enable row level security;
drop policy if exists "miembros ven novandra_config" on public.novandra_config;
create policy "miembros ven novandra_config" on public.novandra_config for select using (public.stockly_es_miembro(id_empresa));
drop policy if exists "admins editan novandra_config" on public.novandra_config;
create policy "admins editan novandra_config" on public.novandra_config for all
  using (public.stockly_es_admin(id_empresa)) with check (public.stockly_es_admin(id_empresa));
insert into public.novandra_config (id_empresa) select id from public."Empresa" on conflict do nothing;

create or replace function public.tg_empresa_novandra()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into novandra_config (id_empresa) values (new.id) on conflict do nothing;
  return new;
end $$;
drop trigger if exists empresa_novandra on public."Empresa";
create trigger empresa_novandra after insert on public."Empresa"
  for each row execute function public.tg_empresa_novandra();

-- Módulos nuevos para permisos de empleados.
insert into public.modulos (nombre)
select n from unnest(array['Sucursales', 'Inteligencia']) as n
where not exists (select 1 from public.modulos m where m.nombre = n);
insert into public.permisos (id_usuario, idmodulo)
select u.id, m.id from public."Usuarios" u cross join public.modulos m
where lower(coalesce(u.tipouser, '')) in ('dueño', 'administrador', 'admin')
  and m.nombre in ('Sucursales', 'Inteligencia')
  and not exists (select 1 from public.permisos p where p.id_usuario = u.id and p.idmodulo = m.id);

grant execute on function public.stockly_rotacion(bigint, int, bigint), public.stockly_auditoria_resumen(bigint, int),
  public.stockly_dashboard(bigint, int, bigint) to authenticated;
