-- =====================================================================
-- Stockly v2: planes y suscripción, bodegas, clientes, proveedores,
-- ventas y facturación, órdenes de compra, notificaciones y Novandra.
--
-- Los planes van en "stockly_planes" y "stockly_suscripciones" para no
-- chocar con tablas "planes"/"suscripciones" que ya existían en la base.
--
-- Se ejecuta sobre la base existente (Empresa, Usuarios, asignarempresa,
-- modulos, permisos, productos, kardex). Es idempotente: se puede volver
-- a ejecutar sin duplicar datos.
--
-- Supuesto importante: el stock total de "productos" lo mantiene el
-- trigger que ya existe sobre "kardex" (el mismo que usa la página Kardex).
-- Aquí solo se registra en kardex y se lleva la distribución por bodega.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Utilidades de acceso
-- ---------------------------------------------------------------------
create or replace function public.stockly_id_usuario()
returns bigint
language sql stable security definer set search_path = public
as $$
  select id from "Usuarios" where idauth::text = auth.uid()::text limit 1
$$;

create or replace function public.stockly_es_miembro(_id_empresa bigint)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from asignarempresa a
    where a.id_empresa = _id_empresa and a.id_usuario = public.stockly_id_usuario()
  )
$$;

create or replace function public.stockly_es_admin(_id_empresa bigint)
returns boolean
language sql stable security definer set search_path = public
as $$
  select public.stockly_es_miembro(_id_empresa) and exists (
    select 1 from "Usuarios" u
    where u.id = public.stockly_id_usuario()
      and lower(coalesce(u.tipouser, '')) in ('dueño', 'administrador', 'admin')
  )
$$;

-- ---------------------------------------------------------------------
-- Planes y suscripción
-- ---------------------------------------------------------------------
create table if not exists public.stockly_planes (
  id text primary key,
  nombre text not null,
  descripcion text,
  precio_mensual numeric(12, 2) not null default 0,
  precio_anual numeric(12, 2) not null default 0,
  -- null = ilimitado
  limite_productos int,
  limite_bodegas int,
  limite_usuarios int,
  limite_ventas_mes int,
  limite_novandra_mes int,
  factura_electronica boolean not null default false,
  reportes_avanzados boolean not null default false,
  orden int not null default 0,
  destacado boolean not null default false
);

insert into public.stockly_planes as p
  (id, nombre, descripcion, precio_mensual, precio_anual, limite_productos, limite_bodegas,
   limite_usuarios, limite_ventas_mes, limite_novandra_mes, factura_electronica, reportes_avanzados, orden, destacado)
values
  ('basico', 'Básico', 'Para empezar a ordenar tu inventario.', 0, 0, 100, 1, 2, 300, 30, false, false, 1, false),
  ('pro', 'Pro', 'Para negocios con varias sedes y ventas diarias.', 89000, 890000, 2000, 5, 10, null, 500, true, true, 2, true),
  ('empresa', 'Empresa', 'Sin límites, con Novandra a tope.', 249000, 2490000, null, null, null, null, 3000, true, true, 3, false)
on conflict (id) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion,
  precio_mensual = excluded.precio_mensual, precio_anual = excluded.precio_anual,
  limite_productos = excluded.limite_productos, limite_bodegas = excluded.limite_bodegas,
  limite_usuarios = excluded.limite_usuarios, limite_ventas_mes = excluded.limite_ventas_mes,
  limite_novandra_mes = excluded.limite_novandra_mes, factura_electronica = excluded.factura_electronica,
  reportes_avanzados = excluded.reportes_avanzados, orden = excluded.orden, destacado = excluded.destacado;

create table if not exists public.stockly_suscripciones (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null unique references public."Empresa"(id) on delete cascade,
  id_plan text not null default 'basico' references public.stockly_planes(id),
  ciclo text not null default 'mensual' check (ciclo in ('mensual', 'anual')),
  estado text not null default 'activa' check (estado in ('activa', 'prueba', 'cancelada')),
  inicio timestamptz not null default now(),
  renovacion timestamptz not null default (now() + interval '1 month'),
  created_at timestamptz not null default now()
);

create table if not exists public.historial_suscripcion (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  plan_anterior text,
  plan_nuevo text not null,
  ciclo text not null,
  id_usuario bigint,
  fecha timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Bodegas
-- ---------------------------------------------------------------------
create table if not exists public.bodegas (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  nombre text not null,
  tipo text not null default 'satelite' check (tipo in ('principal', 'punto_venta', 'ecommerce', 'satelite')),
  direccion text,
  responsable text,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  unique (id_empresa, nombre)
);
create unique index if not exists bodegas_una_principal on public.bodegas (id_empresa) where tipo = 'principal';

-- Cantidades de las bodegas que NO son la principal. La principal se calcula:
-- stock total del producto - lo que está en las demás bodegas.
create table if not exists public.stock_bodega (
  id_bodega bigint not null references public.bodegas(id) on delete cascade,
  id_producto bigint not null references public.productos(id) on delete cascade,
  cantidad numeric(14, 3) not null default 0 check (cantidad >= 0),
  primary key (id_bodega, id_producto)
);

create table if not exists public.traslados (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_producto bigint not null references public.productos(id) on delete cascade,
  id_origen bigint not null references public.bodegas(id) on delete cascade,
  id_destino bigint not null references public.bodegas(id) on delete cascade,
  cantidad numeric(14, 3) not null check (cantidad > 0),
  id_usuario bigint,
  nota text,
  fecha timestamptz not null default now()
);

alter table public.kardex add column if not exists id_bodega bigint references public.bodegas(id) on delete set null;

create or replace view public.v_stock_bodega
with (security_invoker = true) as
select b.id as id_bodega, b.id_empresa, b.nombre as bodega, b.tipo,
       p.id as id_producto, p.descripcion, p.stock_minimo, p.precioventa, p.preciocompra,
       case when b.tipo = 'principal'
            then greatest(p.stock - coalesce((
                   select sum(sb.cantidad) from public.stock_bodega sb
                   join public.bodegas o on o.id = sb.id_bodega
                   where sb.id_producto = p.id and o.tipo <> 'principal'), 0), 0)
            else coalesce(sb.cantidad, 0)
       end as cantidad
from public.bodegas b
join public.productos p on p.id_empresa = b.id_empresa
left join public.stock_bodega sb on sb.id_bodega = b.id and sb.id_producto = p.id;

create or replace function public.stockly_disponible(_id_bodega bigint, _id_producto bigint)
returns numeric
language sql stable security definer set search_path = public
as $$
  select coalesce((select cantidad from public.v_stock_bodega
                   where id_bodega = _id_bodega and id_producto = _id_producto), 0)
$$;

create or replace function public.stockly_bodega_principal(_id_empresa bigint)
returns bigint
language sql stable security definer set search_path = public
as $$
  select id from public.bodegas where id_empresa = _id_empresa and tipo = 'principal' limit 1
$$;

-- ---------------------------------------------------------------------
-- Clientes y proveedores
-- ---------------------------------------------------------------------
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  nombre text not null,
  tipo_documento text not null default 'CC' check (tipo_documento in ('CC', 'NIT', 'CE', 'PAS', 'TI')),
  documento text,
  email text,
  telefono text,
  direccion text,
  created_at timestamptz not null default now()
);
create unique index if not exists clientes_documento_unico
  on public.clientes (id_empresa, tipo_documento, documento) where documento is not null;

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  nombre text not null,
  nit text,
  contacto text,
  email text,
  telefono text,
  direccion text,
  created_at timestamptz not null default now(),
  unique (id_empresa, nombre)
);

-- ---------------------------------------------------------------------
-- Facturación
-- ---------------------------------------------------------------------
create table if not exists public.config_facturacion (
  id_empresa bigint primary key references public."Empresa"(id) on delete cascade,
  razon_social text,
  nit text,
  regimen text default 'No responsable de IVA',
  direccion text,
  telefono text,
  email text,
  prefijo text not null default 'FV',
  consecutivo int not null default 0,
  iva_defecto numeric(5, 2) not null default 19,
  nota_pie text,
  -- Factura electrónica DIAN: preparada, se conecta con un proveedor tecnológico.
  electronica_activa boolean not null default false,
  proveedor_dian text check (proveedor_dian in ('alegra', 'siigo', 'facture', 'otro')),
  ambiente text not null default 'pruebas' check (ambiente in ('pruebas', 'produccion')),
  resolucion_numero text,
  resolucion_fecha date,
  rango_desde int,
  rango_hasta int,
  updated_at timestamptz not null default now()
);

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_bodega bigint not null references public.bodegas(id),
  id_cliente bigint references public.clientes(id) on delete set null,
  id_usuario bigint,
  prefijo text not null,
  numero int not null,
  fecha timestamptz not null default now(),
  canal text not null default 'mostrador' check (canal in ('mostrador', 'online', 'telefono', 'otro')),
  metodo_pago text not null default 'efectivo'
    check (metodo_pago in ('efectivo', 'tarjeta', 'transferencia', 'nequi', 'daviplata', 'credito')),
  subtotal numeric(14, 2) not null default 0,
  descuento numeric(14, 2) not null default 0,
  impuesto numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  estado text not null default 'pagada' check (estado in ('pagada', 'pendiente', 'anulada')),
  nota text,
  created_at timestamptz not null default now(),
  unique (id_empresa, prefijo, numero)
);
create index if not exists ventas_empresa_fecha on public.ventas (id_empresa, fecha desc);

create table if not exists public.detalle_venta (
  id bigint generated by default as identity primary key,
  id_venta bigint not null references public.ventas(id) on delete cascade,
  id_producto bigint references public.productos(id) on delete set null,
  descripcion text not null,
  cantidad numeric(14, 3) not null check (cantidad > 0),
  precio_unitario numeric(14, 2) not null,
  descuento numeric(14, 2) not null default 0,
  iva numeric(5, 2) not null default 0,
  total numeric(14, 2) not null
);

create table if not exists public.facturas (
  id bigint generated by default as identity primary key,
  id_venta bigint not null unique references public.ventas(id) on delete cascade,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  prefijo text not null,
  numero int not null,
  tipo text not null default 'interna' check (tipo in ('interna', 'electronica')),
  estado text not null default 'emitida' check (estado in ('emitida', 'anulada')),
  estado_dian text not null default 'no_aplica'
    check (estado_dian in ('no_aplica', 'pendiente', 'enviada', 'aceptada', 'rechazada')),
  cufe text,
  respuesta_dian jsonb,
  emitida_en timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Órdenes de compra (pedidos a proveedores)
-- ---------------------------------------------------------------------
create table if not exists public.ordenes_compra (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_proveedor bigint references public.proveedores(id) on delete set null,
  id_bodega bigint not null references public.bodegas(id),
  numero int not null,
  estado text not null default 'borrador' check (estado in ('borrador', 'enviada', 'recibida', 'cancelada')),
  fecha timestamptz not null default now(),
  fecha_esperada date,
  total numeric(14, 2) not null default 0,
  nota text,
  creada_por text not null default 'usuario' check (creada_por in ('usuario', 'novandra')),
  id_usuario bigint,
  recibida_en timestamptz,
  unique (id_empresa, numero)
);

create table if not exists public.detalle_orden_compra (
  id bigint generated by default as identity primary key,
  id_orden bigint not null references public.ordenes_compra(id) on delete cascade,
  id_producto bigint not null references public.productos(id) on delete cascade,
  descripcion text not null,
  cantidad numeric(14, 3) not null check (cantidad > 0),
  costo_unitario numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0
);

-- ---------------------------------------------------------------------
-- Notificaciones y uso de Novandra
-- ---------------------------------------------------------------------
create table if not exists public.notificaciones (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_usuario bigint,
  tipo text not null default 'sistema' check (tipo in ('venta', 'stock_bajo', 'compra', 'sistema', 'novandra', 'plan')),
  titulo text not null,
  mensaje text,
  enlace text,
  leida boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notificaciones_empresa_fecha on public.notificaciones (id_empresa, created_at desc);

create table if not exists public.novandra_uso (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_usuario bigint,
  fecha timestamptz not null default now(),
  tokens_entrada int not null default 0,
  tokens_salida int not null default 0
);

-- ---------------------------------------------------------------------
-- Seguridad (RLS): cada empresa solo ve lo suyo
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['stockly_suscripciones', 'historial_suscripcion', 'bodegas', 'traslados', 'clientes',
                           'proveedores', 'config_facturacion', 'ventas', 'facturas', 'ordenes_compra',
                           'notificaciones', 'novandra_uso']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "miembros %1$s" on public.%1$I', t);
    execute format(
      'create policy "miembros %1$s" on public.%1$I for all
         using (public.stockly_es_miembro(id_empresa))
         with check (public.stockly_es_miembro(id_empresa))', t);
  end loop;
end $$;

alter table public.stockly_planes enable row level security;
drop policy if exists "stockly_planes visibles" on public.stockly_planes;
create policy "stockly_planes visibles" on public.stockly_planes for select using (true);

alter table public.stock_bodega enable row level security;
drop policy if exists "miembros stock_bodega" on public.stock_bodega;
create policy "miembros stock_bodega" on public.stock_bodega for all
  using (exists (select 1 from public.bodegas b where b.id = id_bodega and public.stockly_es_miembro(b.id_empresa)))
  with check (exists (select 1 from public.bodegas b where b.id = id_bodega and public.stockly_es_miembro(b.id_empresa)));

alter table public.detalle_venta enable row level security;
drop policy if exists "miembros detalle_venta" on public.detalle_venta;
create policy "miembros detalle_venta" on public.detalle_venta for all
  using (exists (select 1 from public.ventas v where v.id = id_venta and public.stockly_es_miembro(v.id_empresa)))
  with check (exists (select 1 from public.ventas v where v.id = id_venta and public.stockly_es_miembro(v.id_empresa)));

alter table public.detalle_orden_compra enable row level security;
drop policy if exists "miembros detalle_orden_compra" on public.detalle_orden_compra;
create policy "miembros detalle_orden_compra" on public.detalle_orden_compra for all
  using (exists (select 1 from public.ordenes_compra o where o.id = id_orden and public.stockly_es_miembro(o.id_empresa)))
  with check (exists (select 1 from public.ordenes_compra o where o.id = id_orden and public.stockly_es_miembro(o.id_empresa)));

-- El plan solo lo cambia la función cambiar_plan.
drop policy if exists "miembros stockly_suscripciones" on public.stockly_suscripciones;
create policy "miembros stockly_suscripciones" on public.stockly_suscripciones for select using (public.stockly_es_miembro(id_empresa));

-- ---------------------------------------------------------------------
-- Datos iniciales por empresa (existentes y nuevas)
-- ---------------------------------------------------------------------
create or replace function public.stockly_inicializar_empresa(_id_empresa bigint)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.bodegas (id_empresa, nombre, tipo)
  select _id_empresa, 'Bodega principal', 'principal'
  where not exists (select 1 from public.bodegas where id_empresa = _id_empresa and tipo = 'principal');

  insert into public.stockly_suscripciones (id_empresa) values (_id_empresa) on conflict (id_empresa) do nothing;

  insert into public.config_facturacion (id_empresa, razon_social)
  select _id_empresa, e.nombre from public."Empresa" e where e.id = _id_empresa
  on conflict (id_empresa) do nothing;
end $$;

create or replace function public.tg_empresa_inicializar()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.stockly_inicializar_empresa(new.id);
  return new;
end $$;

drop trigger if exists empresa_inicializar on public."Empresa";
create trigger empresa_inicializar after insert on public."Empresa"
  for each row execute function public.tg_empresa_inicializar();

select public.stockly_inicializar_empresa(id) from public."Empresa";

-- ---------------------------------------------------------------------
-- Límites del plan
-- ---------------------------------------------------------------------
create or replace function public.stockly_plan(_id_empresa bigint)
returns public.stockly_planes
language sql stable security definer set search_path = public
as $$
  select * from public.stockly_planes
  where id = coalesce((select id_plan from public.stockly_suscripciones where id_empresa = _id_empresa), 'basico')
$$;

create or replace function public.tg_bodegas_limite()
returns trigger language plpgsql security definer set search_path = public
as $$
declare _limite int;
begin
  _limite := (public.stockly_plan(new.id_empresa)).limite_bodegas;
  if _limite is not null and (select count(*) from public.bodegas where id_empresa = new.id_empresa) >= _limite then
    raise exception 'Tu plan permite % bodega(s). Mejora tu plan para agregar más.', _limite
      using errcode = 'P0001';
  end if;
  return new;
end $$;

drop trigger if exists bodegas_limite on public.bodegas;
create trigger bodegas_limite before insert on public.bodegas
  for each row when (new.tipo <> 'principal') execute function public.tg_bodegas_limite();

-- Uso actual frente a los límites, para la página del plan y para Novandra.
create or replace function public.stockly_uso_plan(_id_empresa bigint)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare _inicio_mes timestamptz := date_trunc('month', now() at time zone 'America/Bogota') at time zone 'America/Bogota';
begin
  if not public.stockly_es_miembro(_id_empresa) then
    raise exception 'Sin acceso a esta empresa';
  end if;
  return jsonb_build_object(
    'productos', (select count(*) from public.productos where id_empresa = _id_empresa),
    'bodegas', (select count(*) from public.bodegas where id_empresa = _id_empresa),
    'usuarios', (select count(*) from public.asignarempresa where id_empresa = _id_empresa),
    'ventas_mes', (select count(*) from public.ventas where id_empresa = _id_empresa
                     and fecha >= _inicio_mes and estado <> 'anulada'),
    'novandra_mes', (select count(*) from public.novandra_uso where id_empresa = _id_empresa and fecha >= _inicio_mes)
  );
end $$;

create or replace function public.cambiar_plan(_id_empresa bigint, _id_plan text, _ciclo text default 'mensual')
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _plan public.stockly_planes;
  _uso jsonb;
  _anterior text;
begin
  if not public.stockly_es_admin(_id_empresa) then
    raise exception 'Solo el dueño o un administrador puede cambiar el plan';
  end if;
  select * into _plan from public.stockly_planes where id = _id_plan;
  if not found then raise exception 'Plan no válido'; end if;
  if _ciclo not in ('mensual', 'anual') then raise exception 'Ciclo no válido'; end if;

  _uso := public.stockly_uso_plan(_id_empresa);
  if _plan.limite_productos is not null and (_uso->>'productos')::int > _plan.limite_productos then
    raise exception 'Tienes % productos y el plan % permite %.', _uso->>'productos', _plan.nombre, _plan.limite_productos;
  end if;
  if _plan.limite_bodegas is not null and (_uso->>'bodegas')::int > _plan.limite_bodegas then
    raise exception 'Tienes % bodegas y el plan % permite %.', _uso->>'bodegas', _plan.nombre, _plan.limite_bodegas;
  end if;
  if _plan.limite_usuarios is not null and (_uso->>'usuarios')::int > _plan.limite_usuarios then
    raise exception 'Tienes % usuarios y el plan % permite %.', _uso->>'usuarios', _plan.nombre, _plan.limite_usuarios;
  end if;

  select id_plan into _anterior from public.stockly_suscripciones where id_empresa = _id_empresa;
  update public.stockly_suscripciones
     set id_plan = _id_plan, ciclo = _ciclo, estado = 'activa', inicio = now(),
         renovacion = now() + case when _ciclo = 'anual' then interval '1 year' else interval '1 month' end
   where id_empresa = _id_empresa;

  insert into public.historial_suscripcion (id_empresa, plan_anterior, plan_nuevo, ciclo, id_usuario)
  values (_id_empresa, _anterior, _id_plan, _ciclo, public.stockly_id_usuario());

  insert into public.notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
  values (_id_empresa, 'plan', 'Plan actualizado a ' || _plan.nombre,
          'Facturación ' || _ciclo || '. Los nuevos límites ya están activos.', '/configurar/plan');

  return jsonb_build_object('plan', _id_plan, 'ciclo', _ciclo);
end $$;

-- ---------------------------------------------------------------------
-- Kardex por bodega
-- ---------------------------------------------------------------------
create or replace function public.tg_kardex_bodega()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  _fila record;
  _signo int;
  _tipo text;
begin
  if tg_when = 'BEFORE' then
    if new.id_bodega is null then
      new.id_bodega := public.stockly_bodega_principal(new.id_empresa);
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    _fila := old;
  else
    _fila := new;
  end if;
  -- La bodega principal se calcula a partir del stock total: no hay nada que mover.
  if _fila.id_bodega is null
     or (select tipo from public.bodegas where id = _fila.id_bodega) = 'principal' then
    return null;
  end if;

  _tipo := lower(coalesce(_fila.tipo, ''));
  _signo := case when _tipo = 'salida' then -1 else 1 end;
  if tg_op = 'DELETE' then _signo := -_signo; end if;

  insert into public.stock_bodega (id_bodega, id_producto, cantidad)
  values (_fila.id_bodega, _fila.id_producto, greatest(_signo * _fila.cantidad, 0))
  on conflict (id_bodega, id_producto)
  do update set cantidad = greatest(public.stock_bodega.cantidad + _signo * _fila.cantidad, 0);
  return null;
end $$;

drop trigger if exists kardex_bodega_antes on public.kardex;
create trigger kardex_bodega_antes before insert on public.kardex
  for each row execute function public.tg_kardex_bodega();
drop trigger if exists kardex_bodega_despues on public.kardex;
create trigger kardex_bodega_despues after insert or delete on public.kardex
  for each row execute function public.tg_kardex_bodega();

create or replace function public.trasladar_stock(
  _id_producto bigint, _id_origen bigint, _id_destino bigint, _cantidad numeric, _nota text default null)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  _empresa bigint;
  _tipo_origen text;
  _tipo_destino text;
begin
  select id_empresa, tipo into _empresa, _tipo_origen from public.bodegas where id = _id_origen;
  select tipo into _tipo_destino from public.bodegas where id = _id_destino and id_empresa = _empresa;
  if _empresa is null or _tipo_destino is null or not public.stockly_es_miembro(_empresa) then
    raise exception 'Bodegas no válidas';
  end if;
  if _id_origen = _id_destino then raise exception 'Elige dos bodegas distintas'; end if;
  if _cantidad <= 0 then raise exception 'La cantidad debe ser mayor que cero'; end if;
  if public.stockly_disponible(_id_origen, _id_producto) < _cantidad then
    raise exception 'No hay stock suficiente en la bodega de origen (disponible: %)',
      trim_scale(public.stockly_disponible(_id_origen, _id_producto));
  end if;

  if _tipo_origen <> 'principal' then
    update public.stock_bodega set cantidad = cantidad - _cantidad
     where id_bodega = _id_origen and id_producto = _id_producto;
  end if;
  if _tipo_destino <> 'principal' then
    insert into public.stock_bodega (id_bodega, id_producto, cantidad) values (_id_destino, _id_producto, _cantidad)
    on conflict (id_bodega, id_producto) do update set cantidad = public.stock_bodega.cantidad + excluded.cantidad;
  end if;

  insert into public.traslados (id_empresa, id_producto, id_origen, id_destino, cantidad, id_usuario, nota)
  values (_empresa, _id_producto, _id_origen, _id_destino, _cantidad, public.stockly_id_usuario(), _nota);
end $$;

-- ---------------------------------------------------------------------
-- Ventas y facturas
-- ---------------------------------------------------------------------
-- _venta: { id_empresa, id_bodega, id_cliente?, canal, metodo_pago, estado?, nota?,
--           items: [{ id_producto, cantidad, precio_unitario, descuento?, iva? }] }
create or replace function public.registrar_venta(_venta jsonb)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _empresa bigint := (_venta->>'id_empresa')::bigint;
  _bodega bigint := (_venta->>'id_bodega')::bigint;
  _usuario bigint := public.stockly_id_usuario();
  _plan public.stockly_planes;
  _cfg public.config_facturacion;
  _item jsonb;
  _producto record;
  _cantidad numeric;
  _precio numeric;
  _desc numeric;
  _iva numeric;
  _base numeric;
  _subtotal numeric := 0;
  _descuento numeric := 0;
  _impuesto numeric := 0;
  _id_venta bigint;
  _numero int;
  _ventas_mes int;
begin
  if not public.stockly_es_miembro(_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  if not exists (select 1 from public.bodegas where id = _bodega and id_empresa = _empresa and activa) then
    raise exception 'Bodega no válida';
  end if;
  if jsonb_array_length(coalesce(_venta->'items', '[]'::jsonb)) = 0 then
    raise exception 'La venta no tiene productos';
  end if;

  _plan := public.stockly_plan(_empresa);
  if _plan.limite_ventas_mes is not null then
    _ventas_mes := (public.stockly_uso_plan(_empresa)->>'ventas_mes')::int;
    if _ventas_mes >= _plan.limite_ventas_mes then
      raise exception 'Llegaste al límite de % ventas del mes de tu plan %. Mejora tu plan para seguir vendiendo.',
        _plan.limite_ventas_mes, _plan.nombre;
    end if;
  end if;

  -- Consecutivo: bloquea la fila para que dos cajas no tomen el mismo número.
  select * into _cfg from public.config_facturacion where id_empresa = _empresa for update;
  if not found then
    perform public.stockly_inicializar_empresa(_empresa);
    select * into _cfg from public.config_facturacion where id_empresa = _empresa for update;
  end if;
  _numero := _cfg.consecutivo + 1;
  if _cfg.rango_hasta is not null and _numero > _cfg.rango_hasta then
    raise exception 'Se agotó el rango de numeración autorizado (%-%)', _cfg.rango_desde, _cfg.rango_hasta;
  end if;
  update public.config_facturacion set consecutivo = _numero, updated_at = now() where id_empresa = _empresa;

  insert into public.ventas (id_empresa, id_bodega, id_cliente, id_usuario, prefijo, numero, canal, metodo_pago, estado, nota)
  values (_empresa, _bodega, nullif(_venta->>'id_cliente', '')::bigint, _usuario, _cfg.prefijo, _numero,
          coalesce(_venta->>'canal', 'mostrador'), coalesce(_venta->>'metodo_pago', 'efectivo'),
          coalesce(_venta->>'estado', 'pagada'), _venta->>'nota')
  returning id into _id_venta;

  for _item in select * from jsonb_array_elements(_venta->'items') loop
    select id, descripcion into _producto from public.productos
     where id = (_item->>'id_producto')::bigint and id_empresa = _empresa;
    if not found then raise exception 'Producto no válido'; end if;

    _cantidad := (_item->>'cantidad')::numeric;
    _precio := (_item->>'precio_unitario')::numeric;
    _desc := coalesce((_item->>'descuento')::numeric, 0);
    _iva := coalesce((_item->>'iva')::numeric, 0);
    if _cantidad is null or _cantidad <= 0 then raise exception 'Cantidad no válida para %', _producto.descripcion; end if;
    if _precio is null or _precio < 0 or _desc < 0 or _iva < 0 then
      raise exception 'Precio o descuento no válido para %', _producto.descripcion;
    end if;
    if public.stockly_disponible(_bodega, _producto.id) < _cantidad then
      raise exception 'Stock insuficiente de % en esta bodega (disponible: %)',
        _producto.descripcion, trim_scale(public.stockly_disponible(_bodega, _producto.id));
    end if;

    _base := round(_cantidad * _precio - _desc, 2);
    if _base < 0 then raise exception 'El descuento de % supera el valor del producto', _producto.descripcion; end if;
    _subtotal := _subtotal + _cantidad * _precio;
    _descuento := _descuento + _desc;
    _impuesto := _impuesto + round(_base * _iva / 100, 2);

    insert into public.detalle_venta (id_venta, id_producto, descripcion, cantidad, precio_unitario, descuento, iva, total)
    values (_id_venta, _producto.id, _producto.descripcion, _cantidad, _precio, _desc, _iva,
            _base + round(_base * _iva / 100, 2));

    insert into public.kardex (fecha, tipo, id_usuario, cantidad, detalle, id_empresa, id_producto, id_bodega)
    values (now(), 'Salida', _usuario, _cantidad, 'Venta ' || _cfg.prefijo || '-' || _numero, _empresa, _producto.id, _bodega);
  end loop;

  update public.ventas
     set subtotal = round(_subtotal, 2), descuento = round(_descuento, 2), impuesto = round(_impuesto, 2),
         total = round(_subtotal - _descuento + _impuesto, 2)
   where id = _id_venta;

  insert into public.facturas (id_venta, id_empresa, prefijo, numero, tipo, estado_dian)
  values (_id_venta, _empresa, _cfg.prefijo, _numero,
          case when _cfg.electronica_activa then 'electronica' else 'interna' end,
          case when _cfg.electronica_activa then 'pendiente' else 'no_aplica' end);

  insert into public.notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
  values (_empresa, 'venta', 'Nueva venta ' || _cfg.prefijo || '-' || _numero,
          jsonb_array_length(_venta->'items') || ' producto(s) · ' || coalesce(_venta->>'canal', 'mostrador'),
          '/ventas/facturas');

  return jsonb_build_object('id', _id_venta, 'prefijo', _cfg.prefijo, 'numero', _numero,
                            'total', round(_subtotal - _descuento + _impuesto, 2));
end $$;

create or replace function public.anular_venta(_id_venta bigint, _motivo text default null)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  _v public.ventas;
  _d record;
begin
  select * into _v from public.ventas where id = _id_venta for update;
  if not found or not public.stockly_es_miembro(_v.id_empresa) then raise exception 'Venta no encontrada'; end if;
  if _v.estado = 'anulada' then raise exception 'La venta ya está anulada'; end if;

  for _d in select * from public.detalle_venta where id_venta = _id_venta and id_producto is not null loop
    insert into public.kardex (fecha, tipo, id_usuario, cantidad, detalle, id_empresa, id_producto, id_bodega)
    values (now(), 'Entrada', public.stockly_id_usuario(), _d.cantidad,
            'Anulación ' || _v.prefijo || '-' || _v.numero, _v.id_empresa, _d.id_producto, _v.id_bodega);
  end loop;

  update public.ventas set estado = 'anulada', nota = concat_ws(' · ', nota, 'Anulada: ' || _motivo) where id = _id_venta;
  update public.facturas set estado = 'anulada' where id_venta = _id_venta;
end $$;

-- ---------------------------------------------------------------------
-- Órdenes de compra
-- ---------------------------------------------------------------------
-- _orden: { id_empresa, id_proveedor?, id_bodega?, fecha_esperada?, nota?, creada_por?,
--           items: [{ id_producto, cantidad, costo_unitario? }] }
create or replace function public.crear_orden_compra(_orden jsonb)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _empresa bigint := (_orden->>'id_empresa')::bigint;
  _bodega bigint := coalesce(nullif(_orden->>'id_bodega', '')::bigint, public.stockly_bodega_principal(_empresa));
  _id bigint;
  _numero int;
  _item jsonb;
  _p record;
  _cantidad numeric;
  _costo numeric;
begin
  if not public.stockly_es_miembro(_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  if not exists (select 1 from public.bodegas where id = _bodega and id_empresa = _empresa) then
    raise exception 'Bodega no válida';
  end if;
  if jsonb_array_length(coalesce(_orden->'items', '[]'::jsonb)) = 0 then raise exception 'La orden no tiene productos'; end if;

  perform pg_advisory_xact_lock(hashtext('orden_compra_' || _empresa));
  select coalesce(max(numero), 0) + 1 into _numero from public.ordenes_compra where id_empresa = _empresa;

  insert into public.ordenes_compra (id_empresa, id_proveedor, id_bodega, numero, fecha_esperada, nota, creada_por, id_usuario)
  values (_empresa, nullif(_orden->>'id_proveedor', '')::bigint, _bodega, _numero,
          nullif(_orden->>'fecha_esperada', '')::date, _orden->>'nota',
          coalesce(_orden->>'creada_por', 'usuario'), public.stockly_id_usuario())
  returning id into _id;

  for _item in select * from jsonb_array_elements(_orden->'items') loop
    select id, descripcion, preciocompra into _p from public.productos
     where id = (_item->>'id_producto')::bigint and id_empresa = _empresa;
    if not found then raise exception 'Producto no válido'; end if;
    _cantidad := (_item->>'cantidad')::numeric;
    _costo := coalesce((_item->>'costo_unitario')::numeric, _p.preciocompra, 0);
    if _cantidad is null or _cantidad <= 0 then raise exception 'Cantidad no válida para %', _p.descripcion; end if;
    insert into public.detalle_orden_compra (id_orden, id_producto, descripcion, cantidad, costo_unitario, total)
    values (_id, _p.id, _p.descripcion, _cantidad, _costo, round(_cantidad * _costo, 2));
  end loop;

  update public.ordenes_compra
     set total = (select coalesce(sum(total), 0) from public.detalle_orden_compra where id_orden = _id)
   where id = _id;

  return jsonb_build_object('id', _id, 'numero', _numero);
end $$;

create or replace function public.recibir_orden_compra(_id_orden bigint)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  _o public.ordenes_compra;
  _d record;
  _unidades numeric := 0;
begin
  select * into _o from public.ordenes_compra where id = _id_orden for update;
  if not found or not public.stockly_es_miembro(_o.id_empresa) then raise exception 'Orden no encontrada'; end if;
  if _o.estado in ('recibida', 'cancelada') then raise exception 'La orden ya está %', _o.estado; end if;

  for _d in select * from public.detalle_orden_compra where id_orden = _id_orden loop
    insert into public.kardex (fecha, tipo, id_usuario, cantidad, detalle, id_empresa, id_producto, id_bodega)
    values (now(), 'Entrada', public.stockly_id_usuario(), _d.cantidad, 'Orden de compra OC-' || _o.numero,
            _o.id_empresa, _d.id_producto, _o.id_bodega);
    _unidades := _unidades + _d.cantidad;
  end loop;

  update public.ordenes_compra set estado = 'recibida', recibida_en = now() where id = _id_orden;

  insert into public.notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
  values (_o.id_empresa, 'compra', 'Llegó el pedido OC-' || _o.numero,
          trim_scale(_unidades) || ' unidades · ' || (select nombre from public.bodegas where id = _o.id_bodega), '/compras');
end $$;

-- ---------------------------------------------------------------------
-- Notificación automática de stock bajo
-- ---------------------------------------------------------------------
create or replace function public.tg_productos_stock_bajo()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.stock <= coalesce(new.stock_minimo, 0) and old.stock > coalesce(old.stock_minimo, 0) then
    insert into public.notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
    values (new.id_empresa, 'stock_bajo', 'Stock bajo: ' || new.descripcion,
            'Quedan ' || trim_scale(new.stock) || ' unidades (mínimo ' || trim_scale(coalesce(new.stock_minimo, 0)) || ')',
            '/reportes/stock-bajo-minimo');
  end if;
  return new;
end $$;

drop trigger if exists productos_stock_bajo on public.productos;
create trigger productos_stock_bajo after update of stock on public.productos
  for each row execute function public.tg_productos_stock_bajo();

-- ---------------------------------------------------------------------
-- Dashboard
-- ---------------------------------------------------------------------
create or replace function public.stockly_dashboard(_id_empresa bigint, _dias int default 30)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  _hoy date := (now() at time zone 'America/Bogota')::date;
  _desde date := _hoy - (_dias - 1);
  _ventas jsonb;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;

  with dias as (select generate_series(_desde, _hoy, interval '1 day')::date as dia),
       v as (select (fecha at time zone 'America/Bogota')::date as dia, total
               from public.ventas where id_empresa = _id_empresa and estado <> 'anulada'
                and fecha >= (_desde - _dias)::timestamp at time zone 'America/Bogota')
  select jsonb_build_object(
    'serie', (select jsonb_agg(jsonb_build_object('fecha', d.dia,
                'total', coalesce((select sum(total) from v where v.dia = d.dia), 0),
                'ventas', (select count(*) from v where v.dia = d.dia)) order by d.dia) from dias d),
    'total_periodo', (select coalesce(sum(total), 0) from v where dia >= _desde),
    'total_anterior', (select coalesce(sum(total), 0) from v where dia < _desde),
    'num_ventas', (select count(*) from v where dia >= _desde),
    'total_hoy', (select coalesce(sum(total), 0) from v where dia = _hoy),
    'ventas_hoy', (select count(*) from v where dia = _hoy)
  ) into _ventas;

  return _ventas || jsonb_build_object(
    'top_productos', coalesce((
      select jsonb_agg(t) from (
        select dv.id_producto, dv.descripcion, sum(dv.cantidad) as cantidad, sum(dv.total) as total
          from public.detalle_venta dv join public.ventas ve on ve.id = dv.id_venta
         where ve.id_empresa = _id_empresa and ve.estado <> 'anulada'
           and ve.fecha >= _desde::timestamp at time zone 'America/Bogota'
         group by dv.id_producto, dv.descripcion order by sum(dv.cantidad) desc limit 5) t), '[]'::jsonb),
    'por_metodo', coalesce((
      select jsonb_agg(t) from (
        select metodo_pago as metodo, sum(total) as total, count(*) as ventas from public.ventas
         where id_empresa = _id_empresa and estado <> 'anulada'
           and fecha >= _desde::timestamp at time zone 'America/Bogota'
         group by metodo_pago order by sum(total) desc) t), '[]'::jsonb),
    'bodegas', coalesce((
      select jsonb_agg(t order by t.tipo = 'principal' desc, t.nombre) from (
        select b.id, b.nombre, b.tipo, coalesce(sum(s.cantidad), 0) as unidades
          from public.bodegas b left join public.v_stock_bodega s on s.id_bodega = b.id
         where b.id_empresa = _id_empresa and b.activa
         group by b.id, b.nombre, b.tipo) t), '[]'::jsonb),
    'recientes', coalesce((
      select jsonb_agg(t) from (
        select v.id, v.prefijo, v.numero, v.total, v.estado, v.fecha, v.canal, c.nombre as cliente
          from public.ventas v left join public.clientes c on c.id = v.id_cliente
         where v.id_empresa = _id_empresa order by v.fecha desc limit 5) t), '[]'::jsonb),
    'valor_inventario', (select coalesce(sum(stock * preciocompra), 0) from public.productos where id_empresa = _id_empresa),
    'valor_venta_inventario', (select coalesce(sum(stock * precioventa), 0) from public.productos where id_empresa = _id_empresa),
    'bajo_minimo', (select count(*) from public.productos where id_empresa = _id_empresa and stock <= coalesce(stock_minimo, 0)),
    'ordenes_abiertas', (select count(*) from public.ordenes_compra where id_empresa = _id_empresa and estado in ('borrador', 'enviada'))
  );
end $$;

-- ---------------------------------------------------------------------
-- Módulos nuevos para los permisos
-- ---------------------------------------------------------------------
insert into public.modulos (nombre)
select n from unnest(array['Ventas', 'Bodegas', 'Compras', 'Clientes', 'Proveedores', 'Suscripción', 'Facturación']) as n
where not exists (select 1 from public.modulos m where m.nombre = n);

-- Dueños y administradores reciben acceso a los módulos nuevos.
insert into public.permisos (id_usuario, idmodulo)
select u.id, m.id
from public."Usuarios" u
cross join public.modulos m
where lower(coalesce(u.tipouser, '')) in ('dueño', 'administrador', 'admin')
  and m.nombre in ('Ventas', 'Bodegas', 'Compras', 'Clientes', 'Proveedores', 'Suscripción', 'Facturación')
  and not exists (select 1 from public.permisos p where p.id_usuario = u.id and p.idmodulo = m.id);

-- ---------------------------------------------------------------------
-- Tiempo real para la campana de notificaciones
-- ---------------------------------------------------------------------
do $$
begin
  alter publication supabase_realtime add table public.notificaciones;
exception when duplicate_object or undefined_object then null;
end $$;

grant execute on function public.registrar_venta(jsonb), public.anular_venta(bigint, text),
  public.crear_orden_compra(jsonb), public.recibir_orden_compra(bigint),
  public.trasladar_stock(bigint, bigint, bigint, numeric, text), public.cambiar_plan(bigint, text, text),
  public.stockly_dashboard(bigint, int), public.stockly_uso_plan(bigint), public.stockly_plan(bigint),
  public.stockly_es_miembro(bigint), public.stockly_es_admin(bigint), public.stockly_id_usuario() to authenticated;
