-- =====================================================================
-- Stockly: comprobante de pago de la suscripción y registro de eventos de Wompi.
--
-- - Cada pago aprobado recibe un número de comprobante consecutivo (CP-000001) y se
--   marca cuándo se envió el comprobante por correo, para enviarlo una sola vez.
-- - wompi_eventos guarda cada aviso que llega de Wompi (sin datos de tarjeta), para
--   saber si el webhook está llegando y por qué falla. Solo lo leen las funciones.
-- Se puede ejecutar varias veces.
-- =====================================================================

create sequence if not exists public.pagos_suscripcion_recibo_seq;
alter table public.pagos_suscripcion add column if not exists numero_recibo bigint;
alter table public.pagos_suscripcion add column if not exists recibo_enviado_en timestamptz;
create unique index if not exists pagos_suscripcion_numero_recibo on public.pagos_suscripcion (numero_recibo);

-- El número se asigna al aprobarse el pago (los rechazados no consumen números).
create or replace function public.tg_pago_suscripcion_recibo()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if new.estado = 'aprobado' and new.numero_recibo is null then
    new.numero_recibo := nextval('public.pagos_suscripcion_recibo_seq');
  end if;
  return new;
end $$;
drop trigger if exists pago_suscripcion_recibo on public.pagos_suscripcion;
create trigger pago_suscripcion_recibo before insert or update of estado on public.pagos_suscripcion
for each row execute function public.tg_pago_suscripcion_recibo();

-- Pagos aprobados antes de esta migración.
update public.pagos_suscripcion set numero_recibo = nextval('public.pagos_suscripcion_recibo_seq')
 where estado = 'aprobado' and numero_recibo is null;

create table if not exists public.wompi_eventos (
  id bigint generated by default as identity primary key,
  recibido_en timestamptz not null default now(),
  evento text,
  referencia text,
  estado text,
  transaccion text,
  firma_valida boolean,
  resultado text
);
create index if not exists wompi_eventos_referencia on public.wompi_eventos (referencia);
alter table public.wompi_eventos enable row level security;
revoke all on public.wompi_eventos from anon, authenticated;
