-- =====================================================================
-- Stockly: códigos promocionales (plan Pro gratis por un tiempo).
--
-- Un código da el plan Pro por N días sin pagar. Se canjea en Plan y suscripción.
--  * Cada código tiene usos máximos y fecha límite para canjearlo.
--  * Una sola promoción por empresa, y solo si no tiene un plan pagado vigente.
--  * Durante la promoción pueden aplicar topes de seguridad (codigos_promo.limites),
--    pensados para no pasar de los planes gratuitos de Supabase y Brevo. Si la empresa
--    paga, los topes de la promoción dejan de aplicar.
--  * Al terminar, la empresa pasa sola al Básico con todos sus datos; su primera compra
--    sigue teniendo el descuento de primera compra.
-- Los PDF de facturas compartidas cuentan como archivos de la empresa.
-- Requiere 20261023000000_facturas_compartidas.sql. Se puede ejecutar varias veces.
-- =====================================================================

create table if not exists public.codigos_promo (
  codigo text primary key check (codigo = upper(codigo)),
  id_plan text not null references public.stockly_planes(id) default 'pro',
  dias int not null check (dias between 1 and 90),
  usos_max int not null check (usos_max > 0),
  usos int not null default 0,
  canjear_hasta timestamptz not null,
  limites jsonb,                -- topes durante la promoción, p. ej. {"limite_archivos_mb": 40}
  activo boolean not null default true,
  nota text,
  created_at timestamptz not null default now()
);
alter table public.codigos_promo enable row level security;
revoke all on public.codigos_promo from anon, authenticated;

create table if not exists public.canjes_promo (
  id bigint generated by default as identity primary key,
  codigo text not null references public.codigos_promo(codigo),
  id_empresa bigint not null unique references public."Empresa"(id) on delete cascade,
  id_usuario bigint,
  hasta timestamptz not null,
  created_at timestamptz not null default now()
);
alter table public.canjes_promo enable row level security;
drop policy if exists "admins ven su canje" on public.canjes_promo;
create policy "admins ven su canje" on public.canjes_promo for select using (public.stockly_es_admin(id_empresa));

alter table public.stockly_suscripciones add column if not exists promo_codigo text;
alter table public.stockly_suscripciones add column if not exists promo_hasta timestamptz;

-- --------------------------------------------------------------- Canjear
create or replace function public.stockly_canjear_codigo(_id_empresa bigint, _codigo text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  _c public.codigos_promo;
  _s public.stockly_suscripciones;
  _hasta timestamptz;
  _cod text := upper(btrim(coalesce(_codigo, '')));
begin
  if not public.stockly_es_admin(_id_empresa) then raise exception 'Solo el dueño o un administrador puede canjear un código'; end if;
  -- Freno a intentos repetidos: máximo 10 intentos fallidos por hora por empresa se controla en la app;
  -- aquí se evita revelar si el código existe con mensajes distintos de más.
  select * into _c from codigos_promo where codigo = _cod for update;
  if not found or not _c.activo or _c.canjear_hasta < now() then
    raise exception 'Ese código no es válido o ya venció.';
  end if;
  if _c.usos >= _c.usos_max then raise exception 'Ese código ya se usó el máximo de veces.'; end if;
  if exists (select 1 from canjes_promo where id_empresa = _id_empresa) then
    raise exception 'Tu empresa ya usó un código promocional.';
  end if;

  select * into _s from stockly_suscripciones where id_empresa = _id_empresa for update;
  if _s.id_plan <> 'basico' and _s.vence_en is not null and _s.vence_en > now() then
    raise exception 'Ya tienes un plan pagado activo. Puedes usar el código cuando termine.';
  end if;

  _hasta := now() + make_interval(days => _c.dias);
  update stockly_suscripciones
     set id_plan = _c.id_plan, ciclo = 'mensual', estado = 'activa', vence_en = _hasta, renovacion = _hasta,
         promo_codigo = _c.codigo, promo_hasta = _hasta,
         prueba_hasta = least(prueba_hasta, now())   -- la promoción reemplaza la prueba en curso
   where id_empresa = _id_empresa;
  update codigos_promo set usos = usos + 1 where codigo = _c.codigo;
  insert into canjes_promo (codigo, id_empresa, id_usuario, hasta) values (_c.codigo, _id_empresa, public.stockly_id_usuario(), _hasta);
  insert into historial_suscripcion (id_empresa, plan_anterior, plan_nuevo, ciclo, id_usuario)
  values (_id_empresa, _s.id_plan, _c.id_plan, 'mensual', public.stockly_id_usuario());
  insert into notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
  values (_id_empresa, 'plan', 'Código promocional activado',
          'Tienes el plan ' || (select nombre from stockly_planes where id = _c.id_plan) || ' gratis hasta el '
          || to_char(_hasta at time zone 'America/Bogota', 'DD/MM/YYYY')
          || '. No se hará ningún cobro: al terminar pasas al plan Básico gratis con todos tus datos.', '/configurar/plan');
  return jsonb_build_object('ok', true, 'plan', (select nombre from stockly_planes where id = _c.id_plan), 'hasta', _hasta, 'dias', _c.dias);
end $$;
revoke execute on function public.stockly_canjear_codigo(bigint, text) from public, anon;
grant execute on function public.stockly_canjear_codigo(bigint, text) to authenticated;

-- --------------------------------------------------------------- Plan efectivo
-- Igual que en complementos, más los topes de la promoción mientras el periodo vigente
-- sea el de la promoción (si paga, vence_en cambia y los topes dejan de aplicar).
create or replace function public.stockly_plan(_id_empresa bigint)
returns public.stockly_planes
language plpgsql stable security definer set search_path = public
as $$
declare
  _s public.stockly_suscripciones;
  _p public.stockly_planes;
  _extra jsonb;
  _limites jsonb;
begin
  select * into _s from stockly_suscripciones where id_empresa = _id_empresa;
  if _s.id_plan is not null and _s.id_plan <> 'basico' and _s.vence_en is not null and _s.vence_en > now() then
    select * into _p from stockly_planes where id = _s.id_plan;
    if _s.promo_hasta is not null and _s.vence_en = _s.promo_hasta then
      select limites into _limites from codigos_promo where codigo = _s.promo_codigo;
      if _limites is not null then _p := jsonb_populate_record(_p, to_jsonb(_p) || _limites); end if;
      _p.nombre := _p.nombre || ' (promoción)';
    end if;
  elsif _s.prueba_hasta is not null and _s.prueba_hasta > now() then
    select * into _p from stockly_planes where id = 'empresa';
    _p.limite_novandra_mes := 20;
    _p.presupuesto_ia_cop := 5000;
    _p.nombre := 'Enterprise (prueba)';
  else
    select * into _p from stockly_planes where id = 'basico';
  end if;

  select jsonb_object_agg(k, total) into _extra
    from (select inc.key k, sum((inc.value)::numeric * v.cantidad) total
            from public.stockly_complementos_vigentes(_id_empresa) v
            join stockly_complementos c on c.id = v.id_complemento
            cross join lateral jsonb_each(c.incrementos) inc
           group by inc.key) t;
  if _extra is not null then
    select jsonb_object_agg(k, coalesce((to_jsonb(_p) ->> k)::numeric, 0) + (_extra ->> k)::numeric) into _extra
      from jsonb_object_keys(_extra) k;
    _p := jsonb_populate_record(_p, to_jsonb(_p) || _extra);
  end if;
  return _p;
end $$;

-- Estado: añade si el periodo vigente viene de un código promocional.
create or replace function public.stockly_estado_suscripcion(_id_empresa bigint)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  _s public.stockly_suscripciones;
  _p public.stockly_planes;
  _pagado boolean;
  _en_prueba boolean;
  _promo boolean;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin acceso a esta empresa'; end if;
  select * into _s from stockly_suscripciones where id_empresa = _id_empresa;
  _p := public.stockly_plan(_id_empresa);
  _pagado := _s.id_plan <> 'basico' and _s.vence_en is not null and _s.vence_en > now();
  _promo := _pagado and _s.promo_hasta is not null and _s.vence_en = _s.promo_hasta;
  _en_prueba := not _pagado and _s.prueba_hasta is not null and _s.prueba_hasta > now();
  return jsonb_build_object(
    'plan_efectivo', _p.id,
    'plan_nombre', _p.nombre,
    'plan_pagado', case when _pagado then _s.id_plan end,
    'promo', _promo,
    'promo_usada', exists (select 1 from canjes_promo where id_empresa = _id_empresa),
    'ciclo', _s.ciclo,
    'en_prueba', _en_prueba,
    'prueba_hasta', _s.prueba_hasta,
    'prueba_disponible', public.stockly_prueba_disponible(_id_empresa),
    'dias_prueba', coalesce((public.stockly_ajuste('dias_prueba'))::text::int, 7),
    'medio_pago', _s.medio_pago_resumen,
    'vence_en', _s.vence_en,
    'vencido', not _pagado and not _en_prueba and (_s.vence_en is not null or _s.prueba_hasta is not null),
    'dias_restantes', case
      when _pagado then greatest(0, ceil(extract(epoch from _s.vence_en - now()) / 86400))
      when _en_prueba then greatest(0, ceil(extract(epoch from _s.prueba_hasta - now()) / 86400)) end,
    'primera_compra', not exists (select 1 from pagos_suscripcion where id_empresa = _id_empresa and estado = 'aprobado'),
    'descuento_primera_compra', coalesce((public.stockly_ajuste('descuento_primera_compra'))::text::int, 0)
  );
end $$;

-- --------------------------------------------------------------- Archivos (incluye PDF compartidos)
create or replace function public.stockly_archivos_mb(_id_empresa bigint)
returns numeric
language sql stable security definer set search_path = public, storage
as $$
  select round(coalesce(sum((o.metadata->>'size')::bigint), 0) / 1048576.0, 1)
    from storage.objects o
   where o.bucket_id in ('logos', 'facturas-proveedor', 'facturas-compartidas')
     and (storage.foldername(o.name))[1] = _id_empresa::text
$$;
revoke execute on function public.stockly_archivos_mb(bigint) from public, anon;

drop policy if exists "facturas compartidas: subir" on storage.objects;
create policy "facturas compartidas: subir" on storage.objects for insert to authenticated
  with check (bucket_id = 'facturas-compartidas'
              and public.stockly_es_miembro_carpeta((storage.foldername(name))[1])
              and public.stockly_cuota_archivos_ok((storage.foldername(name))[1]));

-- --------------------------------------------------------------- Crear códigos
-- Los códigos NO se guardan en el repositorio. Se crean en el SQL Editor, por ejemplo:
--   insert into public.codigos_promo (codigo, id_plan, dias, usos_max, canjear_hasta, limites, nota) values
--   ('STK-PRO-XXXXXX', 'pro', 30, 1, '2026-12-31 23:59:59-05',
--    '{"limite_ventas_mes": 1500, "limite_productos": 2000, "limite_clientes": 1500, "limite_proveedores": 150,
--      "limite_archivos_mb": 30, "limite_informes_mes": 5, "limite_novandra_mes": 0, "presupuesto_ia_cop": 0}',
--    'Lanzamiento');
-- Ver cuántos se han usado:  select codigo, usos, usos_max from codigos_promo order by codigo;
