-- Red de empresas: consignación, pedidos automáticos y pedidos en borrador.
--  - Envío con modalidad "traslado" (sin cobro) o "consignacion": cada línea lleva un precio de red. Al
--    recibir en consignación, el partner lleva cuenta de lo recibido; cuando lo vende, esa venta queda
--    separada como "por liquidar a la matriz" y se liquida en bloque (la matriz la marca pagada).
--  - Pedido automático: el partner marca productos para reposición; cuando el stock baja del mínimo se crea
--    un pedido en borrador (no toca stock). El partner lo confirma, la matriz despacha, el stock solo cambia
--    al recibir.
--  - El plan Partner beneficia solo a la matriz; los partners conservan su propio plan.
-- Idempotente.

alter table public.red_envios add column if not exists modalidad text not null default 'traslado';
alter table public.red_envios drop constraint if exists red_envios_modalidad_chk;
alter table public.red_envios add constraint red_envios_modalidad_chk check (modalidad in ('traslado', 'consignacion'));
alter table public.red_envios_detalle add column if not exists precio_red numeric;
alter table public.red_pedidos add column if not exists origen text not null default 'manual';
alter table public.red_pedidos drop constraint if exists red_pedidos_estado_check;
alter table public.red_pedidos add constraint red_pedidos_estado_check check (estado in ('borrador', 'pendiente', 'despachado', 'rechazado', 'cancelado'));

create table if not exists public.red_consignaciones (
  id bigint generated by default as identity primary key,
  id_vinculo bigint not null references public.red_vinculos(id) on delete cascade,
  id_envio bigint not null references public.red_envios(id) on delete cascade,
  id_envio_detalle bigint,
  id_matriz bigint not null references public."Empresa"(id) on delete cascade,
  id_partner bigint not null references public."Empresa"(id) on delete cascade,
  id_producto bigint not null references public.productos(id) on delete cascade,
  descripcion text not null,
  cantidad numeric(14, 3) not null,
  vendida numeric(14, 3) not null default 0,
  devuelta numeric(14, 3) not null default 0,
  precio_red numeric not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists red_consignaciones_partner_idx on public.red_consignaciones (id_partner, id_producto);
create table if not exists public.red_consignacion_ventas (
  id bigint generated by default as identity primary key,
  id_consignacion bigint not null references public.red_consignaciones(id) on delete cascade,
  id_venta bigint not null,
  id_detalle_venta bigint,
  cantidad numeric(14, 3) not null,
  precio_red numeric not null,
  total numeric not null,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'liquidada', 'anulada')),
  id_liquidacion bigint,
  created_at timestamptz not null default now()
);
create index if not exists red_consignacion_ventas_venta_idx on public.red_consignacion_ventas (id_venta);
create table if not exists public.red_liquidaciones (
  id bigint generated by default as identity primary key,
  id_vinculo bigint not null references public.red_vinculos(id) on delete cascade,
  id_partner bigint not null references public."Empresa"(id) on delete cascade,
  id_matriz bigint not null references public."Empresa"(id) on delete cascade,
  numero integer not null,
  total numeric not null,
  unidades numeric not null,
  nota text,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'pagada')),
  creado_por bigint,
  created_at timestamptz not null default now(),
  pagada_en timestamptz
);
create table if not exists public.red_reposicion (
  id bigint generated by default as identity primary key,
  id_vinculo bigint not null references public.red_vinculos(id) on delete cascade,
  id_empresa bigint not null references public."Empresa"(id) on delete cascade,
  id_producto bigint not null references public.productos(id) on delete cascade,
  activo boolean not null default true,
  cantidad numeric(14, 3) not null check (cantidad > 0),
  created_at timestamptz not null default now(),
  unique (id_vinculo, id_producto)
);
alter table public.red_consignaciones enable row level security;
alter table public.red_consignacion_ventas enable row level security;
alter table public.red_liquidaciones enable row level security;
alter table public.red_reposicion enable row level security;
drop policy if exists red_consignaciones_leer on public.red_consignaciones;
create policy red_consignaciones_leer on public.red_consignaciones for select to authenticated using (public.stockly_es_miembro(id_matriz) or public.stockly_es_miembro(id_partner));
drop policy if exists red_consignacion_ventas_leer on public.red_consignacion_ventas;
create policy red_consignacion_ventas_leer on public.red_consignacion_ventas for select to authenticated
  using (exists (select 1 from public.red_consignaciones c where c.id = id_consignacion and (public.stockly_es_miembro(c.id_matriz) or public.stockly_es_miembro(c.id_partner))));
drop policy if exists red_liquidaciones_leer on public.red_liquidaciones;
create policy red_liquidaciones_leer on public.red_liquidaciones for select to authenticated using (public.stockly_es_miembro(id_matriz) or public.stockly_es_miembro(id_partner));
drop policy if exists red_reposicion_leer on public.red_reposicion;
create policy red_reposicion_leer on public.red_reposicion for select to authenticated using (public.stockly_es_miembro(id_empresa));

-- ---------------------------------------------------------------- Ventas de mercancía en consignación
-- Cuando el partner vende un producto que tiene en consignación, la venta se reparte sobre las consignaciones
-- abiertas (la más antigua primero) y queda "por liquidar". Si la venta se anula, se revierte.
create or replace function public.tg_consignacion_venta()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  _v public.ventas;
  _c public.red_consignaciones;
  _resta numeric;
  _toma numeric;
begin
  if new.id_producto is null then return null; end if;
  select * into _v from ventas where id = new.id_venta;
  if not found or _v.estado = 'anulada' then return null; end if;
  _resta := new.cantidad;
  for _c in select * from red_consignaciones where id_partner = _v.id_empresa and id_producto = new.id_producto and cantidad - vendida - devuelta > 0 order by created_at, id loop
    exit when _resta <= 0;
    _toma := least(_resta, _c.cantidad - _c.vendida - _c.devuelta);
    insert into red_consignacion_ventas (id_consignacion, id_venta, id_detalle_venta, cantidad, precio_red, total)
    values (_c.id, _v.id, new.id, _toma, _c.precio_red, round(_toma * _c.precio_red, 2));
    update red_consignaciones set vendida = vendida + _toma where id = _c.id;
    _resta := _resta - _toma;
  end loop;
  return null;
end $$;
drop trigger if exists consignacion_venta on public.detalle_venta;
create trigger consignacion_venta after insert on public.detalle_venta for each row execute function public.tg_consignacion_venta();

create or replace function public.tg_consignacion_anulacion()
returns trigger language plpgsql security definer set search_path = public
as $$
declare _cv record;
begin
  if new.estado = 'anulada' and old.estado is distinct from 'anulada' then
    for _cv in select * from red_consignacion_ventas where id_venta = new.id and estado = 'pendiente' loop
      update red_consignaciones set vendida = greatest(vendida - _cv.cantidad, 0) where id = _cv.id_consignacion;
      update red_consignacion_ventas set estado = 'anulada' where id = _cv.id;
    end loop;
  end if;
  return null;
end $$;
drop trigger if exists consignacion_anulacion on public.ventas;
create trigger consignacion_anulacion after update of estado on public.ventas for each row execute function public.tg_consignacion_anulacion();

-- Resumen de consignación para la empresa (como partner o como matriz)
create or replace function public.stockly_red_consignacion(_id_empresa bigint)
returns jsonb language plpgsql stable security definer set search_path = public
as $$
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  return jsonb_build_object(
    'productos', coalesce((select jsonb_agg(to_jsonb(x) order by x.otra, x.descripcion) from (
      select c.id_vinculo, case when c.id_partner = _id_empresa then 'partner' else 'matriz' end as mi_rol,
             case when c.id_partner = _id_empresa then m.nombre else p.nombre end as otra,
             c.id_producto, c.descripcion, c.precio_red,
             sum(c.cantidad) as recibida, sum(c.vendida) as vendida, sum(c.devuelta) as devuelta, sum(c.cantidad - c.vendida - c.devuelta) as disponible,
             coalesce((select sum(cv.total) from red_consignacion_ventas cv join red_consignaciones cc on cc.id = cv.id_consignacion
                        where cc.id_vinculo = c.id_vinculo and cc.id_producto = c.id_producto and cv.estado = 'pendiente'), 0) as por_liquidar
        from red_consignaciones c
        join "Empresa" m on m.id = c.id_matriz
        join "Empresa" p on p.id = c.id_partner
       where _id_empresa in (c.id_partner, c.id_matriz)
       group by c.id_vinculo, c.id_partner, c.id_matriz, m.nombre, p.nombre, c.id_producto, c.descripcion, c.precio_red) x), '[]'::jsonb),
    'por_liquidar', coalesce((select jsonb_agg(to_jsonb(x)) from (
      select c.id_vinculo, case when c.id_partner = _id_empresa then m.nombre else p.nombre end as otra,
             case when c.id_partner = _id_empresa then 'partner' else 'matriz' end as mi_rol,
             sum(cv.total) as total, sum(cv.cantidad) as unidades, count(*) as ventas
        from red_consignacion_ventas cv join red_consignaciones c on c.id = cv.id_consignacion
        join "Empresa" m on m.id = c.id_matriz join "Empresa" p on p.id = c.id_partner
       where cv.estado = 'pendiente' and _id_empresa in (c.id_partner, c.id_matriz)
       group by c.id_vinculo, c.id_partner, c.id_matriz, m.nombre, p.nombre) x), '[]'::jsonb),
    'liquidaciones', coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (
      select l.id, l.numero, l.total, l.unidades, l.estado, l.nota, l.created_at, l.pagada_en, l.id_vinculo,
             case when l.id_partner = _id_empresa then 'partner' else 'matriz' end as mi_rol,
             case when l.id_partner = _id_empresa then m.nombre else p.nombre end as otra
        from red_liquidaciones l join "Empresa" m on m.id = l.id_matriz join "Empresa" p on p.id = l.id_partner
       where _id_empresa in (l.id_partner, l.id_matriz) limit 200) x), '[]'::jsonb));
end $$;

-- El partner liquida lo vendido en consignación de un vínculo (queda pendiente de pago); la matriz la marca pagada.
create or replace function public.stockly_red_liquidar(_id_vinculo bigint, _id_empresa bigint, _nota text default null)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare _v public.red_vinculos; _total numeric; _unid numeric; _id bigint; _numero int; _mi text;
begin
  if not public.stockly_es_admin(_id_empresa) then raise exception 'Solo el dueño o un administrador puede liquidar'; end if;
  _v := public.stockly_red_vinculo(_id_vinculo, _id_empresa);
  if _v.id_partner <> _id_empresa then raise exception 'Solo el partner liquida sus ventas en consignación'; end if;
  select coalesce(sum(cv.total), 0), coalesce(sum(cv.cantidad), 0) into _total, _unid
    from red_consignacion_ventas cv join red_consignaciones c on c.id = cv.id_consignacion
   where c.id_vinculo = _id_vinculo and cv.estado = 'pendiente';
  if _unid <= 0 then raise exception 'No hay ventas en consignación por liquidar'; end if;
  select coalesce(max(numero), 0) + 1 into _numero from red_liquidaciones where id_partner = _id_empresa;
  insert into red_liquidaciones (id_vinculo, id_partner, id_matriz, numero, total, unidades, nota, creado_por)
  values (_id_vinculo, _id_empresa, _v.id_matriz, _numero, _total, _unid, nullif(btrim(_nota), ''), public.stockly_id_usuario()) returning id into _id;
  update red_consignacion_ventas cv set estado = 'liquidada', id_liquidacion = _id
    from red_consignaciones c where c.id = cv.id_consignacion and c.id_vinculo = _id_vinculo and cv.estado = 'pendiente';
  select nombre into _mi from "Empresa" where id = _id_empresa;
  perform public.stockly_red_notificar(_v.id_matriz, _mi || ' liquidó su consignación LIQ-' || _numero, trim_scale(_unid) || ' unidades · ' || to_char(_total, 'FM999G999G999G999') || '. Márcala como pagada cuando recibas el dinero.');
  return jsonb_build_object('id', _id, 'numero', _numero, 'total', _total, 'unidades', _unid);
end $$;
create or replace function public.stockly_red_liquidacion_pagada(_id bigint, _id_empresa bigint)
returns void language plpgsql security definer set search_path = public
as $$
declare _l public.red_liquidaciones; _mi text;
begin
  if not public.stockly_es_admin(_id_empresa) then raise exception 'Solo el dueño o un administrador puede confirmar pagos'; end if;
  select * into _l from red_liquidaciones where id = _id and id_matriz = _id_empresa for update;
  if not found then raise exception 'Liquidación no encontrada'; end if;
  if _l.estado = 'pagada' then raise exception 'Ya está pagada'; end if;
  update red_liquidaciones set estado = 'pagada', pagada_en = now() where id = _id;
  select nombre into _mi from "Empresa" where id = _id_empresa;
  perform public.stockly_red_notificar(_l.id_partner, _mi || ' confirmó el pago de LIQ-' || _l.numero, 'Consignación al día.');
end $$;

-- ---------------------------------------------------------------- Reposición automática
create or replace function public.stockly_red_reposicion(_id_empresa bigint, _id_vinculo bigint)
returns jsonb language plpgsql stable security definer set search_path = public
as $$
declare _v public.red_vinculos;
begin
  _v := public.stockly_red_vinculo(_id_vinculo, _id_empresa);
  return coalesce((select jsonb_agg(to_jsonb(x) order by x.descripcion) from (
    select p.id as id_producto, coalesce(p.nombre_completo, p.descripcion) as descripcion, p.stock, p.stock_minimo, p.unidad, p.presentacion,
           coalesce(r.activo, false) as activo, r.cantidad,
           exists (select 1 from red_pedidos pe join red_pedidos_detalle d on d.id_pedido = pe.id
                    where pe.id_vinculo = _id_vinculo and pe.id_solicitante = _id_empresa and pe.estado in ('borrador', 'pendiente') and d.id_producto_solicitante = p.id) as pedido_abierto
      from productos p
      left join red_reposicion r on r.id_vinculo = _id_vinculo and r.id_producto = p.id
     where p.id_empresa = _id_empresa) x), '[]'::jsonb);
end $$;
create or replace function public.stockly_red_reposicion_config(_id_vinculo bigint, _id_empresa bigint, _id_producto bigint, _activo boolean, _cantidad numeric)
returns void language plpgsql security definer set search_path = public
as $$
declare _v public.red_vinculos;
begin
  if not public.stockly_es_admin(_id_empresa) then raise exception 'Solo el dueño o un administrador configura la reposición'; end if;
  _v := public.stockly_red_vinculo(_id_vinculo, _id_empresa);
  if not exists (select 1 from productos where id = _id_producto and id_empresa = _id_empresa) then raise exception 'Producto no encontrado'; end if;
  if coalesce(_cantidad, 0) <= 0 then raise exception 'Indica cuánto pedir'; end if;
  insert into red_reposicion (id_vinculo, id_empresa, id_producto, activo, cantidad) values (_id_vinculo, _id_empresa, _id_producto, coalesce(_activo, true), _cantidad)
  on conflict (id_vinculo, id_producto) do update set activo = excluded.activo, cantidad = excluded.cantidad;
end $$;

-- Al bajar del mínimo: pedido en borrador (sin tocar stock) si no hay uno abierto para ese producto y vínculo.
create or replace function public.tg_red_reposicion_auto()
returns trigger language plpgsql security definer set search_path = public
as $$
declare _r record; _id bigint; _numero int; _otra bigint; _otra_nombre text;
begin
  if coalesce(new.stock, 0) > coalesce(new.stock_minimo, 0) then return null; end if;
  for _r in select r.*, v.id_matriz, v.id_partner from red_reposicion r join red_vinculos v on v.id = r.id_vinculo
             where r.id_producto = new.id and r.activo and v.estado = 'activo' loop
    continue when exists (select 1 from red_pedidos pe join red_pedidos_detalle d on d.id_pedido = pe.id
                           where pe.id_vinculo = _r.id_vinculo and pe.id_solicitante = _r.id_empresa and pe.estado in ('borrador', 'pendiente') and d.id_producto_solicitante = new.id);
    _otra := case when _r.id_matriz = _r.id_empresa then _r.id_partner else _r.id_matriz end;
    select nombre into _otra_nombre from "Empresa" where id = _otra;
    select coalesce(max(numero), 0) + 1 into _numero from red_pedidos where id_solicitante = _r.id_empresa;
    insert into red_pedidos (id_vinculo, id_solicitante, id_proveedor, numero, estado, origen, nota)
    values (_r.id_vinculo, _r.id_empresa, _otra, _numero, 'borrador', 'automatico', 'Reposición automática: ' || coalesce(new.nombre_completo, new.descripcion) || ' bajó del mínimo')
    returning id into _id;
    insert into red_pedidos_detalle (id_pedido, id_producto_solicitante, descripcion, codigointerno, codigobarras, cantidad)
    values (_id, new.id, coalesce(new.nombre_completo, new.descripcion), new.codigointerno::text, new.codigobarras::text, _r.cantidad);
    insert into notificaciones (id_empresa, tipo, titulo, mensaje, enlace)
    values (_r.id_empresa, 'red', 'Pedido automático listo para confirmar', coalesce(new.nombre_completo, new.descripcion) || ' bajó del mínimo. Pedido RED-' || _numero || ' a ' || _otra_nombre || ' en borrador: confírmalo en Red de empresas.', '/red');
  end loop;
  return null;
end $$;
drop trigger if exists red_reposicion_auto on public.productos;
create trigger red_reposicion_auto after update of stock on public.productos for each row execute function public.tg_red_reposicion_auto();

-- Confirmar un pedido en borrador (pasa a pendiente y la otra empresa lo ve)
create or replace function public.stockly_red_confirmar_pedido(_id_pedido bigint, _id_empresa bigint)
returns void language plpgsql security definer set search_path = public
as $$
declare _p public.red_pedidos; _mi text;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  select * into _p from red_pedidos where id = _id_pedido and id_solicitante = _id_empresa for update;
  if not found then raise exception 'Pedido no encontrado'; end if;
  if _p.estado <> 'borrador' then raise exception 'El pedido ya está %', _p.estado; end if;
  update red_pedidos set estado = 'pendiente' where id = _id_pedido;
  select nombre into _mi from "Empresa" where id = _id_empresa;
  perform public.stockly_red_notificar(_p.id_proveedor, 'Pedido de ' || _mi, 'Pedido RED-' || _p.numero || ' con ' || (select count(*) from red_pedidos_detalle where id_pedido = _id_pedido) || ' producto(s). Atiéndelo en Red de empresas.');
end $$;

grant execute on function public.stockly_red_consignacion(bigint) to authenticated;
grant execute on function public.stockly_red_liquidar(bigint, bigint, text) to authenticated;
grant execute on function public.stockly_red_liquidacion_pagada(bigint, bigint) to authenticated;
grant execute on function public.stockly_red_reposicion(bigint, bigint) to authenticated;
grant execute on function public.stockly_red_reposicion_config(bigint, bigint, bigint, boolean, numeric) to authenticated;
grant execute on function public.stockly_red_confirmar_pedido(bigint, bigint) to authenticated;

-- ---------------------------------------------------------------- Funciones existentes con modalidad, precio de red y borradores
drop function if exists public.stockly_red_enviar(bigint, bigint, bigint, jsonb, text, bigint);
CREATE OR REPLACE FUNCTION public.stockly_red_enviar(_id_vinculo bigint, _id_empresa bigint, _id_bodega bigint, _items jsonb, _nota text DEFAULT NULL::text, _id_pedido bigint DEFAULT NULL::bigint, _modalidad text DEFAULT 'traslado')
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  _v public.red_vinculos;
  _otra bigint;
  _cfg jsonb;
  _bodega bigint;
  _it jsonb;
  _p public.productos;
  _cant numeric;
  _id bigint;
  _numero int;
  _unidades numeric := 0;
  _mi_nombre text;
  _otro_nombre text;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  _v := public.stockly_red_vinculo(_id_vinculo, _id_empresa);
  _otra := public.stockly_red_otra(_v, _id_empresa);
  _cfg := public.stockly_red_config(_v, _id_empresa);
  _bodega := coalesce(_id_bodega, public.stockly_bodega_principal(_id_empresa));
  if not exists (select 1 from bodegas where id = _bodega and id_empresa = _id_empresa) then raise exception 'Bodega no válida'; end if;
  if _items is null or jsonb_typeof(_items) <> 'array' or jsonb_array_length(_items) = 0 then raise exception 'Agrega al menos un producto'; end if;
  if _id_pedido is not null and not exists (select 1 from red_pedidos where id = _id_pedido and id_proveedor = _id_empresa and id_vinculo = _id_vinculo and estado = 'pendiente') then
    raise exception 'Pedido no encontrado, en borrador o ya atendido';
  end if;
  select nombre into _mi_nombre from "Empresa" where id = _id_empresa;
  select nombre into _otro_nombre from "Empresa" where id = _otra;
  select coalesce(max(numero), 0) + 1 into _numero from red_envios where id_origen = _id_empresa;

  if coalesce(_modalidad, 'traslado') not in ('traslado', 'consignacion') then raise exception 'Modalidad no válida'; end if;
  insert into red_envios (id_vinculo, id_origen, id_destino, numero, id_bodega_origen, id_pedido, nota, creado_por, modalidad)
  values (_id_vinculo, _id_empresa, _otra, _numero, _bodega, _id_pedido, nullif(btrim(_nota), ''), public.stockly_id_usuario(), coalesce(_modalidad, 'traslado'))
  returning id into _id;

  for _it in select * from jsonb_array_elements(_items) loop
    select * into _p from productos where id = (_it->>'id_producto')::bigint and id_empresa = _id_empresa;
    if not found then raise exception 'Producto no encontrado'; end if;
    _cant := (_it->>'cantidad')::numeric;
    if _cant is null or _cant <= 0 then raise exception 'Cantidad no válida para %', _p.descripcion; end if;
    if public.stockly_disponible(_bodega, _p.id) < _cant then
      raise exception 'Stock insuficiente de % en esta bodega (disponible: %)', _p.descripcion, trim_scale(public.stockly_disponible(_bodega, _p.id));
    end if;
    insert into red_envios_detalle (id_envio, id_producto_origen, descripcion, codigointerno, codigobarras, cantidad, costo_unitario, precio_venta, categoria, marca, stock_minimo, unidad, presentacion, contenido, contenido_unidad, precio_red)
    values (_id, _p.id, _p.descripcion, _p.codigointerno::text, _p.codigobarras::text, _cant,
            case when coalesce((_cfg->>'costos')::boolean, false) then _p.preciocompra end, _p.precioventa,
            (select descripcion from categorias where id = _p.id_categoria), (select descripcion from marca where id = _p.idmarca), _p.stock_minimo, _p.unidad, _p.presentacion, _p.contenido, _p.contenido_unidad,
            case when coalesce(_modalidad, 'traslado') = 'consignacion' then coalesce(nullif(_it->>'precio_red', '')::numeric, _p.precioventa) end);
    insert into kardex (tipo, cantidad, detalle, id_empresa, id_producto, id_bodega, origen, referencia, nota)
    values ('Salida', _cant, 'Envío a ' || _otro_nombre || ' RED-' || _numero, _id_empresa, _p.id, _bodega, 'red', _id, nullif(btrim(_nota), ''));
    _unidades := _unidades + _cant;
  end loop;

  if _id_pedido is not null then
    update red_pedidos set estado = 'despachado', atendido_en = now() where id = _id_pedido;
  end if;
  perform public.stockly_red_notificar(_otra, 'Mercancía en camino de ' || _mi_nombre,
    trim_scale(_unidades) || ' unidades · envío RED-' || _numero || '. Recíbelo en Red de empresas.');
  perform public.stockly_auditar(_id_empresa, 'envio_red', 'red_envios', _id,
    jsonb_build_object('destino', _otro_nombre, 'numero', _numero, 'unidades', _unidades, 'nota', _nota), null, _bodega, _unidades, null);
  return jsonb_build_object('id', _id, 'numero', _numero, 'unidades', _unidades);
end $function$;
grant execute on function public.stockly_red_enviar(bigint, bigint, bigint, jsonb, text, bigint, text) to authenticated;
CREATE OR REPLACE FUNCTION public.stockly_red_recibir(_id_envio bigint, _id_empresa bigint, _id_bodega bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  _e public.red_envios;
  _d record;
  _bodega bigint;
  _idp bigint;
  _creados int := 0;
  _unidades numeric := 0;
  _origen_nombre text;
  _mi_nombre text;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  select * into _e from red_envios where id = _id_envio and id_destino = _id_empresa for update;
  if not found then raise exception 'Envío no encontrado'; end if;
  if _e.estado <> 'enviado' then raise exception 'Este envío ya fue %', _e.estado; end if;
  _bodega := coalesce(_id_bodega, public.stockly_bodega_principal(_id_empresa));
  if not exists (select 1 from bodegas where id = _bodega and id_empresa = _id_empresa) then raise exception 'Bodega no válida'; end if;
  select nombre into _origen_nombre from "Empresa" where id = _e.id_origen;
  select nombre into _mi_nombre from "Empresa" where id = _id_empresa;

  for _d in select * from red_envios_detalle where id_envio = _id_envio loop
    _idp := public.stockly_red_buscar_producto(_id_empresa, _d.codigointerno, _d.codigobarras, _d.descripcion);
    if _idp is null then
      _idp := public.stockly_red_crear_producto(_id_empresa, _d.descripcion, _d.codigointerno, _d.codigobarras, _d.precio_venta, _d.costo_unitario, _d.categoria, _d.marca, _d.stock_minimo, _d.unidad, _d.presentacion, _d.contenido, _d.contenido_unidad);
      _creados := _creados + 1;
    end if;
    update red_envios_detalle set id_producto_destino = _idp where id = _d.id;
    insert into kardex (tipo, cantidad, detalle, id_empresa, id_producto, id_bodega, origen, referencia, nota)
    values ('Entrada', _d.cantidad, 'Recibido de ' || _origen_nombre || ' RED-' || _e.numero, _id_empresa, _idp, _bodega, 'red', _e.id, _e.nota);
    _unidades := _unidades + _d.cantidad;
    if _e.modalidad = 'consignacion' then
      insert into red_consignaciones (id_vinculo, id_envio, id_envio_detalle, id_matriz, id_partner, id_producto, descripcion, cantidad, precio_red)
      values (_e.id_vinculo, _e.id, _d.id, _e.id_origen, _id_empresa, _idp, _d.descripcion, _d.cantidad, coalesce(_d.precio_red, 0));
    end if;
  end loop;
  update red_envios set estado = 'recibido', id_bodega_destino = _bodega, recibido_por = public.stockly_id_usuario(), recibido_en = now() where id = _id_envio;
  perform public.stockly_red_notificar(_e.id_origen, _mi_nombre || ' recibió tu envío RED-' || _e.numero, trim_scale(_unidades) || ' unidades entraron a su inventario.');
  perform public.stockly_auditar(_id_empresa, 'recepcion_red', 'red_envios', _id_envio,
    jsonb_build_object('origen', _origen_nombre, 'numero', _e.numero, 'unidades', _unidades, 'productos_creados', _creados), null, _bodega, _unidades, null);
  return jsonb_build_object('id', _id_envio, 'unidades', _unidades, 'productos_creados', _creados);
end $function$;
CREATE OR REPLACE FUNCTION public.stockly_red_pedidos(_id_empresa bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  return coalesce((select jsonb_agg(to_jsonb(x) order by x.estado in ('borrador', 'pendiente') desc, x.created_at desc) from (
    select p.id, p.numero, p.estado, p.nota, p.respuesta, p.created_at, p.atendido_en, p.id_vinculo, p.origen,
           case when p.id_solicitante = _id_empresa then 'hecho' else 'recibido' end as direccion,
           case when p.id_solicitante = _id_empresa then pr.nombre else s.nombre end as otra,
           u.nombres as usuario,
           (select coalesce(sum(cantidad), 0) from red_pedidos_detalle x where x.id_pedido = p.id) as unidades,
           (select jsonb_agg(jsonb_build_object('descripcion', x.descripcion, 'codigointerno', x.codigointerno, 'codigobarras', x.codigobarras, 'cantidad', x.cantidad,
                   'id_producto', case when p.id_proveedor = _id_empresa then public.stockly_red_buscar_producto(_id_empresa, x.codigointerno, x.codigobarras, x.descripcion) else x.id_producto_solicitante end) order by x.id)
              from red_pedidos_detalle x where x.id_pedido = p.id) as items
      from red_pedidos p
      join "Empresa" s on s.id = p.id_solicitante
      join "Empresa" pr on pr.id = p.id_proveedor
      left join "Usuarios" u on u.id = p.creado_por
     where _id_empresa in (p.id_solicitante, p.id_proveedor)
       and (p.estado <> 'borrador' or p.id_solicitante = _id_empresa)
     limit 500) x), '[]'::jsonb);
end $function$;
CREATE OR REPLACE FUNCTION public.stockly_red_envios(_id_empresa bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  return coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (
    select e.id, e.numero, e.estado, e.nota, e.motivo_rechazo, e.created_at, e.recibido_en, e.id_vinculo, e.id_pedido, e.modalidad,
           case when e.id_origen = _id_empresa then 'enviado' else 'recibido' end as direccion,
           case when e.id_origen = _id_empresa then d.nombre else o.nombre end as otra,
           bo.nombre as bodega_origen, bd.nombre as bodega_destino, u.nombres as usuario,
           (select coalesce(sum(cantidad), 0) from red_envios_detalle x where x.id_envio = e.id) as unidades,
           (select jsonb_agg(jsonb_build_object('descripcion', x.descripcion, 'codigointerno', x.codigointerno, 'cantidad', x.cantidad, 'precio_venta', x.precio_venta, 'costo_unitario', x.costo_unitario, 'precio_red', x.precio_red) order by x.id)
              from red_envios_detalle x where x.id_envio = e.id) as items
      from red_envios e
      join "Empresa" o on o.id = e.id_origen
      join "Empresa" d on d.id = e.id_destino
      left join bodegas bo on bo.id = e.id_bodega_origen
      left join bodegas bd on bd.id = e.id_bodega_destino
      left join "Usuarios" u on u.id = e.creado_por
     where _id_empresa in (e.id_origen, e.id_destino)
     limit 500) x), '[]'::jsonb);
end $function$;
CREATE OR REPLACE FUNCTION public.stockly_red_pedido_estado(_id_pedido bigint, _id_empresa bigint, _estado text, _respuesta text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  _p public.red_pedidos;
  _nombre text;
begin
  if not public.stockly_es_miembro(_id_empresa) then raise exception 'Sin permiso'; end if;
  select * into _p from red_pedidos where id = _id_pedido for update;
  if not found then raise exception 'Pedido no encontrado'; end if;
  if _p.estado not in ('pendiente', 'borrador') then raise exception 'El pedido ya está %', _p.estado; end if;
  if _p.estado = 'borrador' and _estado <> 'cancelado' then raise exception 'El pedido aún está en borrador'; end if;
  select nombre into _nombre from "Empresa" where id = _id_empresa;
  if _estado = 'rechazado' and _p.id_proveedor = _id_empresa then
    update red_pedidos set estado = 'rechazado', respuesta = nullif(btrim(_respuesta), ''), atendido_en = now() where id = _id_pedido;
    perform public.stockly_red_notificar(_p.id_solicitante, _nombre || ' no puede atender tu pedido RED-' || _p.numero, coalesce(nullif(btrim(_respuesta), ''), 'Pedido rechazado.'));
  elsif _estado = 'cancelado' and _p.id_solicitante = _id_empresa then
    update red_pedidos set estado = 'cancelado', atendido_en = now() where id = _id_pedido;
    if _p.estado = 'pendiente' then perform public.stockly_red_notificar(_p.id_proveedor, _nombre || ' canceló el pedido RED-' || _p.numero, 'Ya no es necesario atenderlo.'); end if;
  else
    raise exception 'Acción no permitida';
  end if;
end $function$;
